"""Gym workouts: barbells, dumbbells, machines, cables, benches and cardio machines."""
from entry import E
from poses import *  # noqa: F401,F403

G = "gym"
GYM = ["gym", "जिम"]
CHEST_KW = ["chest", "chhati", "छाती", "seena", *GYM]
BACK_KW = ["back", "peeth", "पीठ", "lats", "wings", *GYM]
SH_KW = ["shoulders", "kandhe", "कंधे", *GYM]
ARM_KW = ["arms", "baju", "बाजू", *GYM]
LEG_KW = ["legs", "pair", "पैर", "jangh", "जांघ", *GYM]
GLUTE_KW = ["glutes", "kulhe", "कूल्हे", "hips", *GYM]

BENCH = dict(torso=-90, ll=(90, 0), la=(180, 180))          # lying on a bench, feet on the floor, arms up
BENCH_LOW = dict(torso=-90, ll=(90, 0), la=(-150, 150))     # bar lowered to the chest
INCLINE = dict(torso=-130, ll=(90, 0), la=(150, 150))
INCLINE_LOW = dict(torso=-130, ll=(90, 0), la=(-140, 120))
SEATED = dict(torso=180, ll=(90, 0), la=(0, 0))              # sitting on a bench/machine
SEATED_PRESS_LOW = dict(torso=180, ll=(90, 0), la=(-90, 180))
SEATED_PRESS_UP = dict(torso=180, ll=(90, 0), la=(175, 180))
PULLDOWN_TOP = dict(torso=170, ll=(90, 0), la=(170, 175))
PULLDOWN_LOW = dict(torso=165, ll=(90, 0), la=(-60, 160))
ROW_REACH = dict(torso=175, ll=(80, 85), la=(90, 90))         # seated row, arms forward, legs out
ROW_PULL = dict(torso=185, ll=(80, 85), la=(-80, 90))
DEADLIFT_LOW = dict(torso=120, ll=(50, -15), la=(0, 0))

ENTRIES = [
    # ── Chest ──
    E("bench_press", G, "Chest", "Barbell Bench Press", "बेंच प्रेस", "bench press, bench",
      ["chest", "triceps", "shoulders"], ["barbell", "bench"], "intermediate", "4 × 6–10",
      ["Lie on the bench, eyes under the bar, feet flat.", "Grip slightly wider than shoulders, squeeze the shoulder blades together.",
       "Lower the bar to the lower chest with control.", "Press up and slightly back over the shoulders."],
      ["Bouncing the bar off the chest", "Feet off the floor", "Flaring elbows to 90°"],
      ["shoulder injury (use dumbbells or a spotter)"], [*CHEST_KW, "bench", "barbell", "strength"],
      side(BENCH, BENCH_LOW), aliases=["Bench Press", "Flat Bench Press"]),
    E("dumbbell_bench_press", G, "Chest", "Dumbbell Bench Press", "डंबल बेंच प्रेस", "dumbbell press, db bench",
      ["chest", "triceps", "shoulders"], ["dumbbells", "bench"], "beginner", "3 × 8–12",
      ["Lie on a bench with a dumbbell in each hand at chest level.", "Press up until the arms are straight, weights over the shoulders.",
       "Lower slowly with elbows about 45° from the body."],
      ["Clanking the dumbbells", "Going too heavy too early"],
      ["shoulder pain"], [*CHEST_KW, "dumbbell", "beginner"],
      side(BENCH_LOW, BENCH), aliases=["Dumbbell Bench Press"]),
    E("incline_dumbbell_press", G, "Chest", "Incline Dumbbell Press", "इनक्लाइन डंबल प्रेस", "incline press, incline bench",
      ["chest", "shoulders", "triceps"], ["dumbbells", "bench"], "beginner", "3 × 8–12",
      ["Set the bench to about 30°.", "Press the dumbbells up over the upper chest.", "Lower slowly to chest level."],
      ["Bench too steep (turns into a shoulder press)", "Arching off the bench"],
      ["shoulder pain"], [*CHEST_KW, "upper chest", "incline", "dumbbell"],
      side(INCLINE_LOW, INCLINE)),
    E("pec_deck", G, "Chest", "Pec Deck (Chest Fly Machine)", "पेक डेक", "pec deck, butterfly, chest fly machine",
      ["chest", "shoulders"], ["machine"], "beginner", "3 × 12–15",
      ["Sit with your back flat, handles at chest height.", "Bring the arms together in a hugging motion.",
       "Squeeze the chest, then open slowly."],
      ["Shoulders rolling forward", "Letting the weight slam back"],
      ["shoulder injury"], [*CHEST_KW, "butterfly", "machine", "fly"],
      front(dict(la=(80, 120)), dict(la=(60, 160)), [11, 12])),
    E("cable_crossover", G, "Chest", "Cable Crossover", "केबल क्रॉसओवर", "cable fly, crossover",
      ["chest", "shoulders"], ["cable machine"], "intermediate", "3 × 12–15",
      ["Stand between two high cables, one handle in each hand.", "Step forward, slight bend in the elbows.",
       "Bring the hands together in front of the chest, then open slowly."],
      ["Bending the elbows too much", "Using momentum"],
      [], [*CHEST_KW, "cable", "fly", "lower chest"],
      front(dict(la=(110, 110)), dict(la=(30, 25)), [11, 12])),
    E("chest_press_machine", G, "Chest", "Chest Press Machine", "चेस्ट प्रेस मशीन", "chest press machine",
      ["chest", "triceps"], ["machine"], "beginner", "3 × 10–12",
      ["Adjust the seat so handles are at mid-chest.", "Press the handles forward until the arms are almost straight.",
       "Return slowly."],
      ["Shrugging", "Locking the elbows hard"],
      [], [*CHEST_KW, "machine", "beginner"],
      side(dict(SEATED, la=(-60, 90)), dict(SEATED, la=(90, 90)))),
    E("dips", G, "Chest", "Parallel Bar Dips", "डिप्स", "dips, bar dips",
      ["chest", "triceps", "shoulders"], ["machine"], "advanced", "3 × 6–10",
      ["Support yourself on parallel bars, arms straight.", "Lean slightly forward and lower until the elbows are at 90°.",
       "Press back up."],
      ["Going too deep", "Shrugging shoulders to the ears"],
      ["shoulder injury"], [*CHEST_KW, "triceps", "dips", "bodyweight"],
      side(dict(torso=175, ll=(-10, -60), la=(0, 0)), dict(torso=165, ll=(-10, -60), la=(-80, 0)))),

    # ── Back ──
    E("lat_pulldown", G, "Back", "Lat Pulldown", "लैट पुलडाउन", "lat pulldown, pulldown",
      ["back", "biceps"], ["cable machine"], "beginner", "3 × 10–12",
      ["Sit with thighs under the pads, hands wider than shoulders.", "Pull the bar to the upper chest, elbows down and back.",
       "Control the bar back up."],
      ["Pulling behind the neck", "Leaning far back"],
      [], [*BACK_KW, "v shape", "pulldown"],
      side(PULLDOWN_TOP, PULLDOWN_LOW), aliases=["Lat Pulldown"]),
    E("seated_cable_row", G, "Back", "Seated Cable Row", "सीटेड केबल रो", "cable row, seated row",
      ["back", "biceps"], ["cable machine"], "beginner", "3 × 10–12",
      ["Sit tall, feet on the platform, knees slightly bent.", "Pull the handle to your belly, elbows close.",
       "Squeeze the shoulder blades, then extend slowly."],
      ["Rocking the torso", "Rounding the back"],
      ["lower back pain"], [*BACK_KW, "row", "posture"],
      side(ROW_REACH, ROW_PULL), aliases=["Seated Cable Row"]),
    E("chest_supported_row", G, "Back", "Chest-supported Row", "चेस्ट-सपोर्टेड रो", "chest supported row, incline row",
      ["back", "biceps"], ["dumbbells", "bench"], "beginner", "3 × 10–12",
      ["Lie face down on an incline bench with dumbbells hanging.", "Row the weights to your ribs.",
       "Lower slowly."],
      ["Lifting the chest off the pad", "Shrugging"],
      [], [*BACK_KW, "back friendly", "kamar", "row"],
      side(dict(torso=135, ll=(-20, -20), la=(0, 0)), dict(torso=135, ll=(-20, -20), la=(-80, 10))), aliases=["Chest-supported Row"]),
    E("barbell_row", G, "Back", "Barbell Bent-over Row", "बारबेल रो", "barbell row, bent over row",
      ["back", "biceps", "lower back"], ["barbell"], "intermediate", "4 × 6–10",
      ["Hold the bar, hinge forward with a flat back.", "Row the bar to your lower ribs.", "Lower with control."],
      ["Rounding the back", "Standing up during the rep"],
      ["lower back pain"], [*BACK_KW, "barbell", "row", "strength"],
      side(HINGE, HINGE_ROW, [11, 12])),
    E("assisted_pull_up", G, "Back", "Pull-up / Assisted Pull-up", "पुल-अप", "pull up, chin up, assisted pull up",
      ["back", "biceps", "forearms"], ["pull-up bar", "machine"], "intermediate", "3 × 5–10",
      ["Hang from the bar, hands shoulder-width (use the assisted machine or a band if needed).", "Pull your chest towards the bar, elbows down.",
       "Lower all the way with control."],
      ["Kipping or swinging", "Half reps"],
      ["shoulder injury"], [*BACK_KW, "pull up", "chin up", "bodyweight"],
      front(dict(la=(170, 175), ll=(0, 0)), dict(la=(110, 175), ll=(0, 0))), aliases=["Assisted Pull-up", "Pull-up"]),
    E("deadlift", G, "Back", "Deadlift", "डेडलिफ्ट", "deadlift",
      ["back", "glutes", "hamstrings", "lower back"], ["barbell"], "advanced", "4 × 3–6",
      ["Stand with mid-foot under the bar, grip just outside the legs.", "Brace, flat back, push the floor away to stand up.",
       "Lower by pushing the hips back, bar close to the legs."],
      ["Rounding the back", "Bar drifting away from the body", "Jerking the bar"],
      ["back injury", "hernia"], [*BACK_KW, "kamar", "strength", "barbell", "full body"],
      side(DEADLIFT_LOW, STAND, [11, 12])),
    E("trap_bar_deadlift", G, "Back", "Trap-bar Deadlift", "ट्रैप-बार डेडलिफ्ट", "trap bar deadlift, hex bar",
      ["glutes", "quads", "back"], ["barbell"], "intermediate", "4 × 5–8",
      ["Stand inside the trap bar, grip the handles.", "Brace and push the floor away to stand tall.",
       "Lower with control."],
      ["Rounding the back", "Knees caving"],
      ["back injury"], [*BACK_KW, "trap bar", "hex bar", "strength", "beginner friendly"],
      side(dict(torso=135, ll=(55, -20), la=(0, 0)), STAND, [11, 12]), aliases=["Trap-bar Deadlift"]),
    E("back_extension", G, "Back", "Back Extension", "बैक एक्सटेंशन", "hyperextension, back extension",
      ["lower back", "glutes", "hamstrings"], ["machine"], "beginner", "3 × 12",
      ["Set the pad at hip level on the extension bench.", "Lower the torso with a flat back.",
       "Raise until the body is straight — don't over-arch."],
      ["Hyper-arching at the top", "Swinging"],
      ["acute back pain"], ["lower back", "kamar", "कमर", "back pain", *GYM],
      side(dict(torso=20, ll=(-90, -90), la=(0, 0)), dict(torso=90, ll=(-90, -90), la=(-30, 40)))),

    # ── Shoulders ──
    E("overhead_press", G, "Shoulders", "Barbell Overhead Press", "ओवरहेड प्रेस", "overhead press, military press, OHP",
      ["shoulders", "triceps", "core"], ["barbell"], "intermediate", "4 × 5–8",
      ["Bar at the front of the shoulders, grip just outside.", "Squeeze glutes, press the bar straight up past your face.",
       "Lock out overhead, then lower to the shoulders."],
      ["Leaning back", "Pressing forward instead of up"],
      ["shoulder injury", "lower back pain"], [*SH_KW, "barbell", "press", "strength"],
      front(F_PRESS_START, F_ARMS_UP, [11, 12]), aliases=["Overhead Press"]),
    E("dumbbell_shoulder_press", G, "Shoulders", "Dumbbell Shoulder Press", "डंबल शोल्डर प्रेस", "shoulder press, dumbbell press",
      ["shoulders", "triceps"], ["dumbbells", "bench"], "beginner", "3 × 8–12",
      ["Sit tall on a bench, dumbbells at shoulder height.", "Press up until the arms are straight.",
       "Lower slowly, wrists over elbows."],
      ["Arching the back", "Banging the weights together"],
      ["shoulder pain"], [*SH_KW, "dumbbell", "press"],
      front(F_PRESS_START, F_ARMS_UP), aliases=["Dumbbell Shoulder Press"]),
    E("landmine_press", G, "Shoulders", "Landmine Press", "लैंडमाइन प्रेस", "landmine press, half kneeling press",
      ["shoulders", "chest", "core"], ["barbell"], "intermediate", "3 × 8–10 each arm",
      ["Wedge one end of a barbell in a corner; kneel or stand holding the other end at the shoulder.", "Press up and slightly forward.",
       "Lower with control."],
      ["Twisting the torso", "Arching"],
      [], [*SH_KW, "shoulder friendly", "landmine", "core"],
      side(dict(KNEEL_TALL, la=(-30, 160)), dict(KNEEL_TALL, la=(140, 140))), aliases=["Landmine / Half-kneeling Press"]),
    E("lateral_raise_gym", G, "Shoulders", "Cable / Dumbbell Lateral Raise", "लेटरल रेज़", "side raise, lateral raise",
      ["shoulders"], ["dumbbells", "cable machine"], "beginner", "3 × 12–15",
      ["Stand tall with light dumbbells or a low cable.", "Raise the arms out to the sides to shoulder height, elbows soft.",
       "Lower slowly."],
      ["Swinging", "Shrugging"],
      ["shoulder impingement"], [*SH_KW, "side delts", "wide shoulders"],
      front(F_STAND, F_LAT_RAISE, [11, 12])),
    E("face_pull", G, "Shoulders", "Face Pull", "फेस पुल", "face pull",
      ["shoulders", "back"], ["cable machine"], "beginner", "3 × 12–15",
      ["Set a rope at face height.", "Pull the rope towards your face, elbows high and wide.",
       "Squeeze the upper back, return slowly."],
      ["Elbows dropping", "Leaning back"],
      [], [*SH_KW, "posture", "rear delts", "rounded shoulders"],
      front(dict(la=(150, 150)), F_PRESS_START, [11, 12])),
    E("rear_delt_fly", G, "Shoulders", "Rear Delt Fly", "रियर डेल्ट फ्लाई", "reverse fly, rear delt",
      ["shoulders", "back"], ["dumbbells", "machine"], "beginner", "3 × 12–15",
      ["Hinge forward (or use the reverse pec deck).", "Raise the arms out to the sides, slight bend in the elbows.",
       "Lower slowly."],
      ["Using momentum", "Shrugging"],
      [], [*SH_KW, "posture", "rear delts"],
      side(dict(HINGE, la=(0, 0)), dict(HINGE, la=(-80, -80)), [11, 12])),
    E("shrugs", G, "Shoulders", "Shrugs", "श्रग्स", "shrugs, traps",
      ["shoulders", "neck"], ["dumbbells", "barbell"], "beginner", "3 × 12–15",
      ["Stand holding heavy dumbbells at your sides.", "Lift the shoulders straight up towards the ears.",
       "Pause, then lower."],
      ["Rolling the shoulders", "Bending the elbows"],
      ["neck pain"], [*SH_KW, "traps", "gardan"],
      front(F_STAND, F_STAND, [11, 12])),

    # ── Arms ──
    E("barbell_curl", G, "Arms", "Barbell Curl", "बारबेल कर्ल", "barbell curl, bicep curl",
      ["biceps", "forearms"], ["barbell"], "beginner", "3 × 8–12",
      ["Stand holding the bar at hip level, palms up.", "Curl the bar up, elbows fixed at your sides.",
       "Lower slowly."],
      ["Swinging the back", "Elbows moving forward"],
      [], [*ARM_KW, "biceps", "dole", "डोले"],
      side(STAND, dict(la=(0, 165)), [11, 12])),
    E("hammer_curl", G, "Arms", "Hammer Curl", "हैमर कर्ल", "hammer curl",
      ["biceps", "forearms"], ["dumbbells"], "beginner", "3 × 10–12",
      ["Hold dumbbells with palms facing each other.", "Curl up keeping the thumbs on top.",
       "Lower slowly."],
      ["Swinging", "Rushing the lowering"],
      [], [*ARM_KW, "biceps", "dole", "forearms"],
      side(STAND, dict(la=(0, 160)), [11, 12])),
    E("preacher_curl", G, "Arms", "Preacher Curl", "प्रीचर कर्ल", "preacher curl",
      ["biceps"], ["dumbbells", "bench"], "beginner", "3 × 10–12",
      ["Sit with the back of the upper arms on the preacher pad.", "Curl the weight up.",
       "Lower all the way with control."],
      ["Lifting the elbows off the pad", "Dropping the weight fast"],
      ["elbow pain"], [*ARM_KW, "biceps", "dole", "डोले"],
      side(dict(SEATED, la=(60, 60)), dict(SEATED, la=(60, 170)))),
    E("cable_triceps_pushdown", G, "Arms", "Cable Triceps Pushdown", "ट्राइसेप्स पुशडाउन", "triceps pushdown, rope pushdown",
      ["triceps"], ["cable machine"], "beginner", "3 × 12–15",
      ["Stand at a high cable with a rope or bar.", "Elbows pinned to your sides, push down until the arms are straight.",
       "Let the forearms rise slowly."],
      ["Elbows drifting forward", "Leaning over the weight"],
      [], [*ARM_KW, "triceps", "pushdown"],
      side(dict(la=(0, 150)), dict(la=(0, 0)), [11, 12]), aliases=["Cable Triceps Pushdown"]),
    E("skull_crusher", G, "Arms", "Lying Triceps Extension", "स्कल क्रशर", "skull crusher, lying triceps extension",
      ["triceps"], ["barbell", "bench"], "intermediate", "3 × 8–12",
      ["Lie on a bench holding an EZ-bar over the chest.", "Bend only the elbows to lower the bar towards the forehead.",
       "Straighten the arms."],
      ["Elbows flaring", "Moving the upper arms"],
      ["elbow pain"], [*ARM_KW, "triceps", "skull crusher"],
      side(BENCH, dict(BENCH, la=(-170, -60)))),
    E("close_grip_bench", G, "Arms", "Close-grip Bench Press", "क्लोज़-ग्रिप बेंच प्रेस", "close grip bench",
      ["triceps", "chest"], ["barbell", "bench"], "intermediate", "3 × 6–10",
      ["Grip the bar about shoulder-width.", "Lower to the lower chest, elbows tucked.",
       "Press up."],
      ["Grip too narrow (wrist strain)", "Flaring elbows"],
      ["wrist pain", "shoulder injury"], [*ARM_KW, "triceps", "bench", "strength"],
      side(BENCH, BENCH_LOW)),
    E("wrist_curl", G, "Arms", "Wrist Curl", "रिस्ट कर्ल", "wrist curl, forearm curl",
      ["forearms"], ["dumbbells", "bench"], "beginner", "3 × 15",
      ["Sit with forearms on the thighs, wrists past the knees.", "Curl the dumbbells up using only the wrists.",
       "Lower slowly."],
      ["Lifting the forearms"],
      ["wrist injury"], [*ARM_KW, "forearms", "grip", "kalai", "कलाई"],
      side(dict(SEATED, la=(30, 80)), dict(SEATED, la=(30, 100)))),

    # ── Legs ──
    E("back_squat", G, "Legs", "Barbell Back Squat", "बैक स्क्वाट", "back squat, barbell squat",
      ["quads", "glutes", "hamstrings", "core"], ["barbell"], "intermediate", "4 × 5–8",
      ["Bar on the upper back, feet shoulder-width, toes slightly out.", "Brace, then sit down between your hips.",
       "Go to at least parallel with a neutral back.", "Drive up through the whole foot."],
      ["Knees caving in", "Heels rising", "Rounding at the bottom"],
      ["knee injury", "back injury"], [*LEG_KW, "squat", "barbell", "strength", "kulhe"],
      side(dict(la=(-140, 160)), dict(SQUAT, la=(-140, 150)), [11, 12]), aliases=["Back Squat"]),
    E("front_squat", G, "Legs", "Front Squat", "फ्रंट स्क्वाट", "front squat",
      ["quads", "core", "glutes"], ["barbell"], "advanced", "4 × 5–8",
      ["Bar on the front of the shoulders, elbows high.", "Squat down keeping the torso upright.",
       "Drive up, elbows staying high."],
      ["Elbows dropping", "Rounding the upper back"],
      ["knee injury", "wrist pain"], [*LEG_KW, "squat", "quads", "core"],
      side(dict(la=(90, 170)), dict(SQUAT, torso=160, la=(90, 170)), [11, 12])),
    E("leg_press", G, "Legs", "Leg Press", "लेग प्रेस", "leg press",
      ["quads", "glutes", "hamstrings"], ["machine"], "beginner", "3 × 10–12",
      ["Sit with the back flat, feet shoulder-width on the platform.", "Lower until the knees are about 90°.",
       "Press up without locking the knees."],
      ["Lower back lifting off the seat", "Locking the knees"],
      ["knee injury"], [*LEG_KW, "machine", "beginner"],
      side(dict(torso=-130, ll=(170, 20), la=(10, 60)), dict(torso=-130, ll=(140, 140), la=(10, 60))), aliases=["Leg Press"]),
    E("leg_extension", G, "Legs", "Leg Extension", "लेग एक्सटेंशन", "leg extension",
      ["quads"], ["machine"], "beginner", "3 × 12–15",
      ["Sit with the pad on the front of the ankles.", "Straighten the knees fully.",
       "Lower slowly."],
      ["Kicking up fast", "Lifting the hips"],
      ["knee injury (keep it light)"], [*LEG_KW, "quads", "machine"],
      side(dict(SEATED, la=(20, 20)), dict(SEATED, ll=(90, 90), la=(20, 20)))),
    E("leg_curl", G, "Legs", "Leg Curl", "लेग कर्ल", "leg curl, hamstring curl",
      ["hamstrings"], ["machine"], "beginner", "3 × 12–15",
      ["Lie face down (or sit) with the pad behind the ankles.", "Curl the heels towards the glutes.",
       "Lower slowly."],
      ["Lifting the hips", "Rushing"],
      [], [*LEG_KW, "hamstrings", "back of thigh", "machine"],
      side(PRONE, dict(PRONE, ll=(-90, 170)))),
    E("romanian_deadlift", G, "Legs", "Romanian Deadlift", "रोमानियन डेडलिफ्ट", "RDL, romanian deadlift",
      ["hamstrings", "glutes", "lower back"], ["barbell", "dumbbells"], "intermediate", "3 × 8–10",
      ["Stand holding the weight at the thighs.", "Push the hips back with soft knees, sliding the weight down the legs.",
       "Stop when you feel a strong hamstring stretch, flat back.", "Squeeze the glutes to stand."],
      ["Rounding the back", "Bending the knees too much (becomes a squat)"],
      ["lower back pain"], [*LEG_KW, "hamstrings", *GLUTE_KW[:3], "rdl"],
      side(STAND, HINGE, [11, 12]), aliases=["Romanian Deadlift", "RDL"]),
    E("bulgarian_split_squat", G, "Legs", "Bulgarian Split Squat", "बल्गेरियन स्प्लिट स्क्वाट", "bulgarian split squat",
      ["quads", "glutes"], ["dumbbells", "bench"], "intermediate", "3 × 8 each leg",
      ["Rear foot on a bench, front foot a stride ahead.", "Drop straight down until the front thigh is parallel.",
       "Drive up through the front heel."],
      ["Front foot too close", "Leaning sideways"],
      ["knee pain", "poor balance"], [*LEG_KW, "single leg", "balance", *GLUTE_KW[:3]],
      side(SPLIT_SQUAT_TOP, LUNGE, [11]), aliases=["Bulgarian Split Squat"]),
    E("hack_squat", G, "Legs", "Hack Squat", "हैक स्क्वाट", "hack squat",
      ["quads", "glutes"], ["machine"], "intermediate", "3 × 8–12",
      ["Back against the pad, shoulders under the supports.", "Lower until thighs are parallel.",
       "Press up without locking out."],
      ["Heels lifting", "Knees caving"],
      ["knee injury"], [*LEG_KW, "machine", "quads"],
      side(dict(torso=165), dict(SQUAT, torso=160), [11, 12])),
    E("seated_calf_raise", G, "Legs", "Seated Calf Raise", "सीटेड काफ रेज़", "seated calf raise, calf machine",
      ["calves"], ["machine"], "beginner", "3 × 15–20",
      ["Sit with the pad on the thighs, balls of the feet on the step.", "Lower the heels for a stretch.",
       "Rise as high as possible, pause."],
      ["Bouncing", "Short range"],
      [], ["calves", "pindli", "पिंडली", *GYM],
      side(dict(SEATED, la=(20, 60)), dict(SEATED, la=(20, 60)))),

    # ── Glutes ──
    E("hip_thrust", G, "Glutes", "Hip Thrust", "हिप थ्रस्ट", "hip thrust, barbell hip thrust",
      ["glutes", "hamstrings"], ["barbell", "bench"], "intermediate", "3 × 8–12",
      ["Upper back on a bench, bar over the hips (use a pad).", "Feet flat, chin tucked.",
       "Drive the hips up until the body is flat from shoulders to knees; squeeze.", "Lower with control."],
      ["Over-arching the back", "Pushing through the toes"],
      [], [*GLUTE_KW, "butt", "women", "barbell"],
      side(dict(torso=-150, ll=(130, 0), la=(-150, 180)), dict(torso=-95, ll=(95, 0), la=(-120, 160))), aliases=["Hip Thrust"]),
    E("cable_kickback", G, "Glutes", "Cable Glute Kickback", "केबल किकबैक", "glute kickback, cable kickback",
      ["glutes"], ["cable machine"], "beginner", "3 × 12 each leg",
      ["Attach an ankle strap to a low cable; hold the machine.", "Kick the leg straight back, squeezing the glute.",
       "Return slowly without arching."],
      ["Arching the lower back", "Swinging"],
      [], [*GLUTE_KW, "butt", "women", "cable"],
      side(dict(torso=160, la=(60, 60)), dict(torso=160, la=(60, 60), rl=(-45, -45)), [11])),
    E("hip_abduction_machine", G, "Glutes", "Hip Abduction Machine", "हिप एबडक्शन", "abductor machine, outer thigh machine",
      ["glutes", "hips"], ["machine"], "beginner", "3 × 15",
      ["Sit with the pads on the outside of the knees.", "Push the knees apart.",
       "Return slowly."],
      ["Letting the weights slam", "Leaning forward"],
      [], [*GLUTE_KW, "outer thigh", "women", "machine"],
      front(dict(torso=180, ll=(90, 0), la=(10, 4)), dict(torso=180, ll=(90, 0), la=(10, 4), spread=6))),
    E("kettlebell_swing", G, "Glutes", "Kettlebell Swing", "केटलबेल स्विंग", "kettlebell swing, kb swing",
      ["glutes", "hamstrings", "core", "cardio"], ["kettlebell"], "intermediate", "4 × 15",
      ["Hinge and hike the kettlebell back between your legs.", "Snap the hips forward to swing it to chest height.",
       "Let it fall back and hinge again."],
      ["Squatting instead of hinging", "Lifting with the arms"],
      ["lower back pain"], [*GLUTE_KW, "kettlebell", "fat loss", "power", "hiit"],
      side(HINGE, dict(la=(90, 90)), [11, 12])),

    # ── Core ──
    E("pallof_press", G, "Core", "Pallof Press", "पैलोफ प्रेस", "pallof press, anti rotation",
      ["core", "obliques"], ["cable machine", "resistance band"], "beginner", "3 × 10 each side",
      ["Stand side-on to a cable at chest height.", "Hold the handle at your chest and press it straight out.",
       "Resist the twist, pause, bring it back."],
      ["Rotating towards the cable", "Leaning away"],
      [], ["core", "pet", "पेट", "obliques", "back safe", *GYM],
      side(dict(la=(0, 160)), STAND_FWD, [11, 12]), aliases=["Pallof Press"]),
    E("cable_crunch", G, "Core", "Cable Crunch", "केबल क्रंच", "cable crunch",
      ["core"], ["cable machine"], "intermediate", "3 × 12–15",
      ["Kneel at a high cable holding the rope beside your head.", "Crunch down, bringing the ribs towards the hips.",
       "Return slowly."],
      ["Pulling with the arms", "Sitting back on the heels"],
      [], ["abs", "pet", "पेट", "six pack", *GYM],
      side(dict(KNEEL_TALL, la=(150, 30)), dict(KNEEL_TALL, torso=110, la=(110, 0)))),
    E("hanging_knee_raise", G, "Core", "Hanging Knee Raise", "हैंगिंग नी रेज़", "hanging leg raise, knee raise",
      ["core", "hips"], ["pull-up bar"], "intermediate", "3 × 8–12",
      ["Hang from a bar (or use the captain's chair).", "Bring the knees up towards the chest without swinging.",
       "Lower slowly."],
      ["Swinging", "Dropping the legs"],
      ["shoulder injury"], ["abs", "lower abs", "pet", "पेट", *GYM],
      side(dict(la=(180, 180)), dict(la=(180, 180), ll=(110, 0)))),
    E("ab_wheel", G, "Core", "Ab Wheel Rollout", "एब व्हील", "ab roller, ab wheel",
      ["core", "shoulders"], ["machine"], "advanced", "3 × 6–10",
      ["Kneel holding the wheel under the shoulders.", "Roll forward slowly, keeping the hips in line.",
       "Pull back using the abs."],
      ["Lower back sagging", "Going too far too soon"],
      ["lower back pain"], ["abs", "pet", "पेट", "core", *GYM],
      side(dict(torso=120, ll=(0, -90), la=(20, 20)), dict(torso=100, ll=(-60, -90), la=(110, 110)))),

    # ── Cardio machines ──
    E("treadmill_walk", G, "Cardio machines", "Treadmill (Incline Walk / Jog)", "ट्रेडमिल", "treadmill, incline walk",
      ["cardio", "calves", "glutes"], ["machine"], "beginner", "20–40 min",
      ["Start slow, then raise the speed or incline.", "Walk or jog upright without holding the rails.",
       "Cool down for the last 3–5 minutes."],
      ["Holding the rails", "Overstriding"],
      ["knee pain (keep incline low)"], ["treadmill", "walking", "running", "cardio", "fat loss", "vajan kam", *GYM],
      side(dict(ll=(25, 0), rl=(-20, -30), la=(-25, -10), ra=(25, 50)), dict(ll=(-20, -30), rl=(25, 0), la=(25, 50), ra=(-25, -10)))),
    E("cross_trainer", G, "Cardio machines", "Cross Trainer (Elliptical)", "क्रॉस ट्रेनर", "cross trainer, elliptical",
      ["cardio", "full body"], ["machine"], "beginner", "20–30 min",
      ["Step on and hold the moving handles.", "Push and pull with arms and legs in a smooth rhythm.",
       "Keep the posture upright."],
      ["Leaning on the handles", "Going too slow to raise the heart rate"],
      [], ["elliptical", "cardio", "low impact", "knee friendly", "fat loss", *GYM],
      side(dict(ll=(20, 0), rl=(-15, -10), la=(60, 120)), dict(ll=(-15, -10), rl=(20, 0), la=(20, 120)))),
    E("stationary_bike", G, "Cardio machines", "Stationary Bike", "स्टेशनरी बाइक", "cycle, exercise bike, spin bike",
      ["cardio", "quads"], ["machine"], "beginner", "20–45 min",
      ["Set the seat so the knee is slightly bent at the bottom.", "Pedal at a steady pace; add resistance as you improve.",
       "Try intervals: 30 s hard, 90 s easy."],
      ["Seat too low", "Bouncing on the seat"],
      [], ["cycle", "cycling", "cardio", "knee friendly", "fat loss", "vajan kam", *GYM],
      side(dict(torso=160, ll=(110, 10), rl=(60, -10), la=(80, 80)), dict(torso=160, ll=(60, -10), rl=(110, 10), la=(80, 80)))),
    E("rowing_machine", G, "Cardio machines", "Rowing Machine", "रोइंग मशीन", "rowing machine, rower",
      ["cardio", "back", "quads"], ["machine"], "intermediate", "10–20 min or intervals",
      ["Start with knees bent, arms straight, leaning slightly forward.", "Push with the legs, then lean back, then pull the handle to the ribs.",
       "Return: arms, body, then legs."],
      ["Pulling with arms first", "Rounding the back"],
      ["lower back pain"], ["rowing", "cardio", "back", "full body", "fat loss", *GYM],
      side(dict(torso=165, ll=(140, 20), la=(90, 90)), ROW_PULL), aliases=["Rowing Machine Intervals"]),
    E("stair_climber", G, "Cardio machines", "Stair Climber", "स्टेयर क्लाइंबर", "stair master, stepper",
      ["cardio", "glutes", "quads"], ["machine"], "intermediate", "15–25 min",
      ["Step at a steady pace using the whole foot.", "Stand tall; rest the hands lightly on the rails only for balance.",
       "Increase speed gradually."],
      ["Leaning on the rails", "Tiny steps on the toes"],
      ["knee pain"], ["stairs", "seedhi", "cardio", "glutes", "fat loss", *GYM],
      side(STEP_UP, dict(rl=(70, -10), ll=(0, 0)), [12])),

    # ── Full body ──
    E("farmers_walk", G, "Full body", "Farmer's Walk", "फार्मर्स वॉक", "farmers walk, farmer carry",
      ["forearms", "core", "shoulders", "full body"], ["dumbbells", "kettlebell"], "beginner", "4 × 30–40 m",
      ["Pick up heavy dumbbells, one in each hand.", "Walk tall with short, quick steps.",
       "Keep the shoulders back and core tight."],
      ["Leaning to one side", "Shrugging"],
      [], ["grip", "full body", "core", "posture", "strength", *GYM],
      side(dict(ll=(20, 0), rl=(-15, -10)), dict(ll=(-15, -10), rl=(20, 0)))),
    E("thruster", G, "Full body", "Dumbbell Thruster", "थ्रस्टर", "thruster, squat press",
      ["quads", "shoulders", "glutes", "full body"], ["dumbbells"], "intermediate", "3 × 10",
      ["Hold dumbbells at the shoulders.", "Squat down, then drive up and press the weights overhead in one motion.",
       "Lower to the shoulders as you squat again."],
      ["Pausing between squat and press", "Arching at the top"],
      ["shoulder injury", "knee pain"], ["full body", "fat loss", "hiit", "squat", "press", *GYM],
      side(dict(SQUAT, la=(-30, 170)), STAND_UP)),
    E("clean_and_press", G, "Full body", "Kettlebell Clean & Press", "क्लीन एंड प्रेस", "clean and press",
      ["full body", "shoulders", "glutes"], ["kettlebell", "dumbbells"], "advanced", "3 × 6 each arm",
      ["Hinge and pull the weight up to the shoulder in one smooth motion.", "Press it overhead.",
       "Lower to the shoulder, then back down."],
      ["Curling the weight up", "Arching the back"],
      ["shoulder injury", "lower back pain"], ["full body", "power", "strength", "kettlebell", *GYM],
      side(HINGE, STAND_UP, [11, 12])),
]
