"""Home workouts: bodyweight, household items, a mat, a band or light dumbbells."""
from entry import E
from poses import *  # noqa: F401,F403

H = "home"
LEGS, CHEST, BACK, CORE, CARDIO, MOB, LOW, FULL = ("Legs & glutes", "Chest & arms", "Back & shoulders", "Core & abs",
                                                  "Cardio & HIIT", "Mobility & stretching", "Low impact / seniors", "Full body")
LEG_KW = ["legs", "pair", "पैर", "jangh", "जांघ", "thighs", "ghar par"]
GLUTE_KW = ["glutes", "hips", "kulhe", "कूल्हे", "butt"]
CORE_KW = ["abs", "pet", "पेट", "belly fat", "pet ki charbi", "core"]
NOEQ = ["no equipment", "bina equipment", "ghar par", "at home"]

ENTRIES = [
    # ── Legs & glutes ──
    E("bodyweight_squat", H, LEGS, "Bodyweight Squat", "स्क्वाट", "squat, squats, baithak",
      ["quads", "glutes", "hamstrings"], ["none"], "beginner", "3 × 12–15",
      ["Stand with feet shoulder-width apart, toes slightly out.", "Push your hips back and bend your knees as if sitting on a chair.",
       "Go down until thighs are about parallel to the floor, chest up.", "Push through your whole foot to stand up."],
      ["Knees caving inwards", "Heels lifting off the floor", "Rounding the back"],
      ["sharp knee pain"], ["squat", "baithak", "बैठक", *LEG_KW, *GLUTE_KW, "beginner"],
      side(STAND_FWD, SQUAT, [11, 12]), aliases=["Bodyweight Squat", "Air Squat"]),
    E("hindu_squat", H, LEGS, "Hindu Squat (Baithak)", "बैठक", "baithak, hindu squat, uthak baithak",
      ["quads", "glutes", "calves"], ["none"], "intermediate", "3 × 20–30",
      ["Stand with feet hip-width apart, arms out in front.", "Rise onto the balls of your feet as you squat down, swinging the arms back.",
       "Touch the heels lightly at the bottom, then stand up swinging the arms forward.", "Keep a steady rhythm with your breathing."],
      ["Going too fast and losing balance", "Letting the knees collapse inward"],
      ["knee pain", "ankle injury"], ["baithak", "बैठक", "desi exercise", "akhada", "stamina", *LEG_KW, "calves", "pindli"],
      side(STAND_FWD, dict(SQUAT, la=(-30, -20)), [11, 12])),
    E("box_squat_chair", H, LEGS, "Chair Box Squat", "कुर्सी स्क्वाट", "chair squat, box squat, kursi squat",
      ["quads", "glutes"], ["chair"], "beginner", "3 × 10–12",
      ["Stand in front of a sturdy chair, feet shoulder-width.", "Sit back slowly until your hips lightly touch the chair.",
       "Pause without relaxing, then stand up tall.", "Lower the chair height (or add a cushion) to adjust difficulty."],
      ["Dropping onto the chair", "Rocking forward to stand"],
      [], ["chair", "kursi", "कुर्सी", "knee friendly", "ghutne", "seniors", *LEG_KW, "beginner"],
      side(STAND_FWD, HALF_SQUAT, [11, 12]), aliases=["Box Squat to Bench", "Sit to stand"]),
    E("goblet_squat", H, LEGS, "Goblet Squat", "गॉब्लेट स्क्वाट", "goblet squat, dumbbell squat",
      ["quads", "glutes", "core"], ["dumbbells", "water bottles"], "beginner", "3 × 10–12",
      ["Hold one dumbbell (or a full water can) at your chest with both hands.", "Squat down between your hips, elbows inside the knees.",
       "Keep the chest tall and the weight close.", "Drive up through the heels."],
      ["Letting the weight pull you forward", "Half reps"],
      ["knee pain"], ["squat", "dumbbell", "weight", *LEG_KW, *GLUTE_KW],
      side(dict(la=(-20, 150)), dict(SQUAT, la=(20, 160)), [11, 12]), aliases=["Goblet Squat"]),
    E("sumo_squat", H, LEGS, "Sumo Squat", "सूमो स्क्वाट", "sumo squat, wide squat",
      ["glutes", "quads", "hips"], ["none"], "beginner", "3 × 12–15",
      ["Stand with feet wide, toes turned out.", "Lower straight down, pushing knees out over the toes.",
       "Keep the chest up and back straight.", "Squeeze the glutes to stand."],
      ["Knees caving in", "Leaning far forward"],
      ["groin strain"], ["inner thigh", "andar ki jangh", *LEG_KW, *GLUTE_KW],
      front(F_WIDE, F_GODDESS, [11, 12])),
    E("reverse_lunge", H, LEGS, "Reverse Lunge", "रिवर्स लंज", "reverse lunge, peeche lunge",
      ["quads", "glutes", "hamstrings"], ["none"], "beginner", "3 × 8–10 each leg",
      ["Stand tall, hands on hips.", "Step one foot back and lower until both knees are bent about 90°.",
       "Keep the front shin vertical and torso upright.", "Push through the front heel to return. Alternate legs."],
      ["Front knee shooting past the toes", "Leaning the torso forward"],
      ["knee pain"], ["lunge", "lunges", *LEG_KW, *GLUTE_KW, "balance"],
      side(STAND, LUNGE, [11]), aliases=["Reverse Lunge"]),
    E("walking_lunge", H, LEGS, "Walking Lunge", "वॉकिंग लंज", "walking lunge, chalte hue lunge",
      ["quads", "glutes", "hamstrings"], ["none"], "intermediate", "3 × 10 steps each leg",
      ["Step forward into a lunge, back knee close to the floor.", "Push off the front foot and bring the back leg through into the next lunge.",
       "Take long steps and keep the torso upright.", "Walk 10 steps per leg."],
      ["Short steps that overload the knee", "Wobbling side to side"],
      ["knee pain", "ankle pain"], ["lunge", "walking", *LEG_KW, *GLUTE_KW, "stamina"],
      side(STAND, LUNGE, [11]), aliases=["Walking Lunge"]),
    E("side_lunge", H, LEGS, "Side Lunge", "साइड लंज", "side lunge, lateral lunge",
      ["quads", "glutes", "hips"], ["none"], "beginner", "3 × 8 each side",
      ["Stand with feet together.", "Take a big step to the side and bend that knee, sitting the hips back.",
       "Keep the other leg straight and both feet flat.", "Push back to the start and switch sides."],
      ["Knee going past the toes", "Rounding the back"],
      ["groin strain", "knee pain"], ["lateral", "inner thigh", *LEG_KW, *GLUTE_KW],
      front(F_STAND, dict(ll=(55, -5), rl=(35, 35), spread=4, la=(10, 60)), [11, 12])),
    E("step_up", H, LEGS, "Step-up", "स्टेप-अप", "step up, seedhi exercise",
      ["quads", "glutes"], ["box/step"], "beginner", "3 × 10 each leg",
      ["Stand facing a stair or sturdy low step.", "Place your whole foot on the step.",
       "Drive through that heel to stand up on the step.", "Step down slowly and repeat; switch legs."],
      ["Pushing off with the back foot", "Using a wobbly surface"],
      ["knee pain", "poor balance (hold a rail)"], ["stairs", "seedhi", "सीढ़ी", *LEG_KW, *GLUTE_KW],
      side(STEP_UP, STAND, [12]), aliases=["Step-up (low box)", "Step Up"]),
    E("glute_bridge", H, LEGS, "Glute Bridge", "ग्लूट ब्रिज", "glute bridge, hip bridge",
      ["glutes", "hamstrings", "lower back"], ["mat"], "beginner", "3 × 12–15",
      ["Lie on your back, knees bent, feet flat hip-width apart.", "Press through your heels and lift your hips.",
       "Squeeze the glutes at the top and pause 1 second.", "Lower slowly."],
      ["Arching the lower back", "Pushing through the toes"],
      [], ["glutes", "kulhe", "कूल्हे", "kamar", "back pain", "lower back", "hips", "women", "beginner"],
      side(SUPINE_KNEES, BRIDGE), aliases=["Glute Bridge"]),
    E("single_leg_bridge", H, LEGS, "Single-leg Glute Bridge", "सिंगल लेग ब्रिज", "single leg bridge",
      ["glutes", "hamstrings"], ["mat"], "intermediate", "3 × 8–10 each leg",
      ["Lie on your back, one knee bent, the other leg straight.", "Lift your hips using the bent leg.",
       "Keep the hips level at the top.", "Lower slowly; switch legs."],
      ["Hips tilting", "Arching the back"],
      [], ["glutes", "kulhe", "hips", "balance", *LEG_KW],
      side(dict(SUPINE_KNEES, rl=(100, 100)), dict(BRIDGE, rl=(100, 110)))),
    E("wall_sit", H, LEGS, "Wall Sit", "वॉल सिट", "wall sit, deewar squat",
      ["quads", "glutes"], ["wall"], "beginner", "3 × 20–45 s",
      ["Lean your back flat against a wall.", "Slide down until knees are bent about 90°.",
       "Keep feet flat and knees over the ankles.", "Hold, breathing steadily."],
      ["Knees past the toes", "Holding the breath"],
      ["knee pain", "high blood pressure (keep it short)"], ["wall", "deewar", "दीवार", *LEG_KW, "endurance"],
      side(dict(torso=180), dict(torso=180, ll=(90, 0), la=(0, 0)), [11, 12])),
    E("calf_raise", H, LEGS, "Standing Calf Raise", "काफ रेज़", "calf raise, pindli exercise",
      ["calves"], ["none"], "beginner", "3 × 15–20",
      ["Stand tall, holding a wall or chair for balance.", "Rise up onto the balls of your feet.",
       "Pause at the top, then lower slowly below level if on a step."],
      ["Bouncing quickly", "Rolling onto the outer foot"],
      [], ["calves", "pindli", "पिंडली", "legs", "pair", "ankle", "ghar par"],
      side(STAND, dict(la=(0, 0), ll=(0, 0)), [11, 12]), aliases=["Standing Calf Raise", "Calf Raises"]),
    E("donkey_kick", H, LEGS, "Donkey Kick", "डंकी किक", "donkey kick, glute kickback",
      ["glutes"], ["mat"], "beginner", "3 × 12 each leg",
      ["Start on hands and knees.", "Keeping the knee bent, lift one foot towards the ceiling.",
       "Squeeze the glute at the top without arching the back.", "Lower and repeat; switch legs."],
      ["Arching the lower back", "Swinging the leg"],
      ["wrist pain"], ["glutes", "kulhe", "butt", "hips", "women", "ghar par"],
      side(QUADRUPED, dict(QUADRUPED, rl=(-100, 170)))),
    E("fire_hydrant", H, LEGS, "Fire Hydrant", "फायर हाइड्रेंट", "fire hydrant",
      ["glutes", "hips"], ["mat"], "beginner", "3 × 12 each side",
      ["Start on hands and knees.", "Lift one bent knee out to the side to hip height.",
       "Keep the hips level and core tight.", "Lower slowly; switch sides."],
      ["Shifting weight to one hand", "Rotating the hips"],
      ["wrist pain"], ["glutes", "hips", "kulhe", "outer thigh", "ghar par"],
      side(QUADRUPED, dict(QUADRUPED, rl=(-40, -90)))),

    # ── Chest & arms ──
    E("push_up", H, CHEST, "Push-up", "पुश-अप", "push up, pushup",
      ["chest", "triceps", "shoulders", "core"], ["none"], "beginner", "3 × 8–15",
      ["Hands slightly wider than shoulders, body in a straight line from head to heels.", "Lower your chest towards the floor, elbows about 45° from the body.",
       "Stop just above the floor.", "Press back up without letting the hips sag."],
      ["Hips sagging or piking", "Flaring the elbows out wide", "Half reps"],
      ["wrist pain", "shoulder injury"], ["chest", "chhati", "छाती", "seena", "triceps", "upper body", *NOEQ],
      side(PLANK, PUSHUP_LOW, [5, 6, 11, 12]), aliases=["Push-up", "Push Ups"]),
    E("hindu_pushup", H, CHEST, "Hindu Push-up (Dand)", "दंड", "dand, hindu pushup, dand baithak",
      ["chest", "shoulders", "triceps", "spine"], ["none"], "intermediate", "3 × 8–15",
      ["Start in a downward-dog shape: hands and feet on the floor, hips high.", "Bend the elbows and swoop the chest forward close to the floor.",
       "Finish with arms straight and chest lifted, like a cobra.", "Push the hips back up to the start."],
      ["Rushing through the swoop", "Letting the lower back crunch"],
      ["shoulder injury", "wrist pain", "lower back pain"], ["dand", "दंड", "desi exercise", "akhada", "chest", "chhati", "kandhe", "flexibility"],
      side(DOWN_DOG, COBRA)),
    E("incline_push_up", H, CHEST, "Incline Push-up", "इनक्लाइन पुश-अप", "incline push up, wall push up, table push up",
      ["chest", "triceps", "shoulders"], ["chair"], "beginner", "3 × 10–15",
      ["Place hands on a sturdy table, bed edge or wall.", "Walk the feet back so the body is straight.",
       "Lower your chest to the edge, then press back.", "The higher the surface, the easier it is."],
      ["Hips sagging", "Surface slipping"],
      ["wrist pain"], ["chest", "chhati", "beginner", "easy", "women", "seniors", "ghar par"],
      side(dict(torso=135, ll=(-45, -45), la=(45, 45)), dict(torso=125, ll=(-55, -55), la=(-30, 75)), [11, 12]),
      aliases=["Incline Push-up"]),
    E("knee_push_up", H, CHEST, "Knee Push-up", "घुटनों पर पुश-अप", "knee push up, ghutne pe pushup",
      ["chest", "triceps"], ["mat"], "beginner", "3 × 8–12",
      ["Start on hands and knees, then walk the hands forward so the body is straight from head to knees.", "Lower the chest towards the floor.",
       "Press back up, keeping the hips in line."],
      ["Bending at the hips", "Dropping the head"],
      ["wrist pain"], ["chest", "chhati", "beginner", "women", *NOEQ],
      side(dict(torso=110, ll=(-70, -90), la=(5, 5)), dict(torso=97, ll=(-83, -90), la=(-110, 5)))),
    E("close_grip_push_up", H, CHEST, "Close-grip Push-up", "क्लोज़-ग्रिप पुश-अप", "close grip pushup, diamond pushup",
      ["triceps", "chest", "shoulders"], ["none"], "intermediate", "3 × 6–12",
      ["Hands under the shoulders (or touching in a diamond).", "Lower with elbows brushing the ribs.",
       "Press back up, body straight."],
      ["Elbows flaring", "Sagging hips"],
      ["wrist pain", "elbow pain"], ["triceps", "baju", "बाजू", "arms", "chest", *NOEQ],
      side(PLANK, PUSHUP_LOW, [5, 6, 11, 12]), aliases=["Close-grip Push-up", "Diamond Push-up"]),
    E("chair_dips", H, CHEST, "Chair Dips", "चेयर डिप्स", "chair dips, triceps dips",
      ["triceps", "shoulders", "chest"], ["chair"], "beginner", "3 × 8–12",
      ["Sit on the edge of a sturdy chair, hands beside your hips.", "Slide forward off the seat, knees bent.",
       "Bend the elbows to lower your hips, then press back up."],
      ["Going too deep", "Shoulders shrugging up"],
      ["shoulder pain", "wrist pain"], ["triceps", "baju", "बाजू", "arms", "dips", "chair", "kursi"],
      side(dict(torso=175, ll=(90, 0), la=(-20, 0)), dict(torso=175, ll=(80, -5), la=(-80, -10)), [11, 12])),
    E("dumbbell_floor_press", H, CHEST, "Dumbbell Floor Press", "डंबल फ्लोर प्रेस", "floor press",
      ["chest", "triceps"], ["dumbbells"], "beginner", "3 × 10–12",
      ["Lie on your back, knees bent, a dumbbell in each hand.", "Start with elbows on the floor, then press the weights up.",
       "Lower until the elbows touch the floor, pause, press again."],
      ["Bouncing the elbows", "Arching the back"],
      [], ["chest", "chhati", "dumbbell", "shoulder friendly", "home gym"],
      side(dict(SUPINE_KNEES, la=(0, 180)), dict(SUPINE_KNEES, la=(180, 180))), aliases=["Dumbbell Floor Press"]),
    E("dumbbell_curl", H, CHEST, "Dumbbell Curl", "डंबल कर्ल", "bicep curl, dumbbell curl, dole",
      ["biceps", "forearms"], ["dumbbells", "water bottles"], "beginner", "3 × 10–12",
      ["Stand tall with dumbbells (or filled bottles) at your sides.", "Keeping elbows still, curl the weights up.",
       "Squeeze at the top, lower slowly."],
      ["Swinging the body", "Elbows drifting forward"],
      [], ["biceps", "dole", "डोले", "baju", "arms", "dumbbell", "ghar par"],
      side(STAND, dict(la=(0, 165)), [11, 12]), aliases=["Dumbbell Curl", "Bicep Curl"]),
    E("overhead_triceps_extension", H, CHEST, "Overhead Triceps Extension", "ओवरहेड ट्राइसेप्स एक्सटेंशन", "overhead triceps extension",
      ["triceps"], ["dumbbells", "water bottles"], "beginner", "3 × 10–12",
      ["Hold one dumbbell overhead with both hands.", "Keeping elbows pointing forward, lower it behind your head.",
       "Straighten the arms to press it back up."],
      ["Elbows flaring out", "Arching the back"],
      ["shoulder pain"], ["triceps", "baju", "बाजू", "arms", "dumbbell"],
      side(dict(la=(170, 175)), dict(la=(170, 10)), [11, 12]), aliases=["Overhead Dumbbell Triceps Extension"]),

    # ── Back & shoulders ──
    E("backpack_row", H, BACK, "Backpack Row", "बैकपैक रो", "backpack row, bag row",
      ["back", "biceps"], ["backpack"], "beginner", "3 × 10–12",
      ["Fill a backpack with books and hold it by the handle or straps.", "Hinge forward with a flat back, knees soft.",
       "Pull the bag towards your belly, squeezing the shoulder blades.", "Lower slowly."],
      ["Rounding the back", "Jerking the weight"],
      ["lower back pain"], ["back", "peeth", "पीठ", "posture", "bag", "ghar par"],
      side(HINGE, HINGE_ROW, [11, 12]), aliases=["Backpack Row"]),
    E("one_arm_dumbbell_row", H, BACK, "One-arm Dumbbell Row", "वन-आर्म डंबल रो", "one arm row, dumbbell row",
      ["back", "biceps", "shoulders"], ["dumbbells", "chair"], "beginner", "3 × 10 each arm",
      ["Place one hand and knee on a bench or chair.", "Hold the dumbbell with the other arm hanging.",
       "Row it to your hip, elbow close to the body.", "Lower slowly; switch sides."],
      ["Twisting the torso", "Shrugging"],
      [], ["back", "peeth", "पीठ", "lats", "dumbbell"],
      side(HINGE, HINGE_ROW, [11, 12]), aliases=["One-arm Dumbbell Row"]),
    E("band_pulldown", H, BACK, "Band / Towel Pulldown", "बैंड पुलडाउन", "band pulldown, towel pulldown",
      ["back", "shoulders"], ["resistance band", "towel"], "beginner", "3 × 12–15",
      ["Hold a band or towel overhead, hands wide, pulling it tight.", "Pull your elbows down towards your back pockets.",
       "Squeeze the shoulder blades, then return slowly."],
      ["Shrugging", "Letting the band go slack"],
      [], ["back", "peeth", "lats", "posture", "band", "towel", "tauliya"],
      front(dict(la=(160, 170)), dict(la=(110, 175)), [11, 12]), aliases=["Band / Towel Pulldown"]),
    E("superman", H, BACK, "Superman", "सुपरमैन", "superman exercise",
      ["lower back", "glutes", "back"], ["mat"], "beginner", "3 × 10 (hold 2 s)",
      ["Lie face down, arms stretched overhead.", "Lift arms, chest and legs a few centimetres off the floor.",
       "Hold 2 seconds, lower slowly."],
      ["Cranking the neck up", "Lifting too high"],
      ["lower back injury", "pregnancy"], ["lower back", "kamar", "कमर", "back pain", "posture", "peeth"],
      side(PRONE, SUPERMAN)),
    E("wall_angels", H, BACK, "Wall Angels", "वॉल एंजल्स", "wall angels, wall slides",
      ["shoulders", "back"], ["wall"], "beginner", "2 × 10",
      ["Stand with your back, head and arms against a wall, elbows bent 90°.", "Slide the arms up the wall as far as you can keep contact.",
       "Slide back down slowly."],
      ["Back arching off the wall", "Forcing the range"],
      [], ["posture", "rounded shoulders", "kandhe", "कंधे", "desk job", "office", "neck"],
      front(F_PRESS_START, F_ARMS_UP, [11, 12])),
    E("band_pull_apart", H, BACK, "Band Pull-apart", "बैंड पुल-अपार्ट", "band pull apart",
      ["shoulders", "back"], ["resistance band"], "beginner", "3 × 15",
      ["Hold a band in front at shoulder height, arms straight.", "Pull it apart until it touches your chest.",
       "Squeeze the shoulder blades and return slowly."],
      ["Shrugging", "Bending the elbows a lot"],
      [], ["posture", "kandhe", "कंधे", "shoulders", "band", "office"],
      front(dict(la=(150, 150)), F_ARMS_SIDE, [11, 12])),
    E("dumbbell_lateral_raise", H, BACK, "Lateral Raise", "लेटरल रेज़", "lateral raise, side raise",
      ["shoulders"], ["dumbbells", "water bottles"], "beginner", "3 × 12–15",
      ["Stand holding light weights at your sides.", "Raise the arms out to the sides to shoulder height, elbows soft.",
       "Lower slowly."],
      ["Swinging", "Lifting above shoulder height with shrugging"],
      ["shoulder impingement"], ["shoulders", "kandhe", "कंधे", "dumbbell", "ghar par"],
      front(F_STAND, F_LAT_RAISE, [11, 12])),
    E("pike_push_up", H, BACK, "Pike Push-up", "पाइक पुश-अप", "pike pushup",
      ["shoulders", "triceps"], ["none"], "advanced", "3 × 6–10",
      ["Start in a downward-dog shape, hips high.", "Bend the elbows and lower the top of your head towards the floor between your hands.",
       "Press back up."],
      ["Dropping the hips", "Flaring the elbows"],
      ["shoulder injury", "high blood pressure", "glaucoma"], ["shoulders", "kandhe", "कंधे", "advanced", *NOEQ],
      side(DOWN_DOG, dict(DOWN_DOG, la=(-60, 30), torso=55)), aliases=["Pike Push-up"]),

    # ── Core & abs ──
    E("plank", H, CORE, "Plank", "प्लैंक", "plank",
      ["core", "shoulders", "glutes"], ["mat"], "beginner", "3 × 20–60 s",
      ["Forearms on the floor under the shoulders, legs straight back.", "Lift the hips so the body is a straight line.",
       "Squeeze glutes and pull the ribs down.", "Breathe and hold."],
      ["Hips sagging", "Hips too high", "Holding the breath"],
      ["shoulder injury", "late pregnancy"], [*CORE_KW, "plank", "stability", *NOEQ],
      side(PRONE, FOREARM_PLANK, [5, 6, 11, 12]), aliases=["Plank", "Forearm Plank (home)"]),
    E("side_plank", H, CORE, "Side Plank", "साइड प्लैंक", "side plank",
      ["obliques", "core", "shoulders"], ["mat"], "intermediate", "3 × 15–30 s each side",
      ["Lie on your side, forearm under the shoulder.", "Lift the hips so the body is straight (bend knees to make it easier).",
       "Hold, then switch sides."],
      ["Hips dropping", "Shoulder up to the ear"],
      ["shoulder injury"], ["obliques", "side fat", "love handles", "kamar", *CORE_KW],
      front(dict(torso=110, ll=(-70, -70), la=(-20, 70)), dict(torso=115, ll=(-65, -65), la=(-20, 70), ra=(180, 180))),
      aliases=["Side Plank (knees)", "Side Plank"]),
    E("dead_bug", H, CORE, "Dead Bug", "डेड बग", "dead bug",
      ["core"], ["mat"], "beginner", "3 × 8 each side",
      ["Lie on your back, arms up, knees bent 90° in the air.", "Slowly lower the opposite arm and leg towards the floor.",
       "Keep the lower back pressed down. Return and switch."],
      ["Lower back lifting off the floor", "Moving too fast"],
      ["late pregnancy"], [*CORE_KW, "back safe", "kamar dard", "beginner"],
      side(DEAD_BUG, dict(DEAD_BUG, rl=(100, 95), ra=(-100, -100))), aliases=["Dead Bug"]),
    E("bird_dog", H, CORE, "Bird Dog", "बर्ड डॉग", "bird dog",
      ["core", "lower back", "glutes"], ["mat"], "beginner", "3 × 8 each side",
      ["Start on hands and knees, back flat.", "Reach one arm forward and the opposite leg back.",
       "Hold 2 seconds without tilting the hips, then switch."],
      ["Arching the back", "Rotating the hips"],
      ["wrist pain"], ["kamar dard", "back pain", "कमर", "balance", "core", "posture"],
      side(QUADRUPED, BIRD_DOG), aliases=["Bird Dog"]),
    E("crunch", H, CORE, "Crunch", "क्रंच", "crunch, crunches, sit up",
      ["core"], ["mat"], "beginner", "3 × 12–15",
      ["Lie on your back, knees bent, hands lightly by your ears.", "Curl your shoulders off the floor using your abs.",
       "Lower slowly."],
      ["Pulling on the neck", "Using momentum"],
      ["neck pain", "pregnancy"], [*CORE_KW, "six pack", "crunches"],
      side(SUPINE_KNEES, CRUNCH)),
    E("bicycle_crunch", H, CORE, "Bicycle Crunch", "बाइसिकल क्रंच", "bicycle crunch, cycle crunch",
      ["core", "obliques"], ["mat"], "intermediate", "3 × 10 each side",
      ["Lie on your back, hands by your ears, legs raised.", "Bring one knee in while twisting the opposite elbow towards it.",
       "Switch sides in a slow pedalling motion."],
      ["Yanking the neck", "Going too fast"],
      ["neck pain", "pregnancy"], [*CORE_KW, "obliques", "side fat", "cycle"],
      side(dict(CRUNCH, ll=(120, 120)), dict(CRUNCH, ll=(150, 60), rl=(100, 100)))),
    E("leg_raise", H, CORE, "Lying Leg Raise", "लेग रेज़", "leg raise, tangein uthana",
      ["core", "hips"], ["mat"], "intermediate", "3 × 10–12",
      ["Lie on your back, legs straight, hands under your hips.", "Lift the legs to vertical, keeping them straight.",
       "Lower slowly without letting the back arch."],
      ["Arching the lower back", "Dropping the legs fast"],
      ["lower back pain", "pregnancy"], [*CORE_KW, "lower abs", "neeche ka pet"],
      side(SUPINE, LEGS_UP)),
    E("flutter_kicks", H, CORE, "Flutter Kicks", "फ्लटर किक्स", "flutter kicks",
      ["core", "hips"], ["mat"], "intermediate", "3 × 20–30 s",
      ["Lie on your back, hands under the hips, legs a little off the floor.", "Kick the legs up and down in small, quick movements.",
       "Keep the lower back down."],
      ["Back arching", "Holding the breath"],
      ["lower back pain", "pregnancy"], [*CORE_KW, "lower abs"],
      side(dict(SUPINE, ll=(105, 105), rl=(80, 80)), dict(SUPINE, ll=(80, 80), rl=(105, 105)))),
    E("russian_twist", H, CORE, "Russian Twist", "रशियन ट्विस्ट", "russian twist",
      ["obliques", "core"], ["mat"], "intermediate", "3 × 10 each side",
      ["Sit with knees bent, lean back slightly, chest tall.", "Twist the torso to tap your hands beside one hip, then the other.",
       "Lift the feet to make it harder."],
      ["Rounding the back", "Only moving the arms"],
      ["lower back pain", "pregnancy"], ["obliques", "side fat", "love handles", *CORE_KW],
      side(dict(torso=-160, ll=(120, 20), la=(70, 90)), dict(torso=-150, ll=(120, 20), la=(40, 60)))),
    E("heel_touches", H, CORE, "Heel Touches", "हील टच", "heel touch, ankle taps",
      ["obliques", "core"], ["mat"], "beginner", "3 × 12 each side",
      ["Lie on your back, knees bent, shoulders slightly lifted.", "Reach one hand down to touch the same-side heel, then the other.",
       "Keep the shoulders up the whole set."],
      ["Resting the head between reps", "Pulling with the neck"],
      ["neck pain"], ["obliques", "side fat", *CORE_KW, "beginner"],
      side(dict(CRUNCH, la=(30, 30)), dict(CRUNCH, la=(80, 80)))),

    # ── Cardio & HIIT ──
    E("jumping_jacks", H, CARDIO, "Jumping Jacks", "जंपिंग जैक", "jumping jack, star jumps",
      ["full body", "cardio", "calves"], ["none"], "beginner", "3 × 30–45 s",
      ["Stand with feet together, arms by your sides.", "Jump the feet out while raising the arms overhead.",
       "Jump back to the start. Keep a steady rhythm."],
      ["Landing on flat, stiff legs", "Going too fast too soon"],
      ["knee pain", "pregnancy"], ["cardio", "fat loss", "vajan kam", "वजन कम", "warm up", "calories", *NOEQ],
      front(F_STAND, F_JACK, [11, 12])),
    E("high_knees", H, CARDIO, "High Knees", "हाई नीज़", "high knees, spot running",
      ["cardio", "quads", "core"], ["none"], "intermediate", "3 × 30 s",
      ["Run on the spot, lifting the knees to hip height.", "Pump the arms and stay on the balls of your feet.",
       "Keep the chest up."],
      ["Leaning back", "Landing heavily"],
      ["knee pain", "pregnancy"], ["cardio", "fat loss", "vajan kam", "running", "calories", *NOEQ],
      side(dict(ll=(90, 0), la=(-40, 60), ra=(40, 120)), dict(rl=(90, 0), ra=(-40, 60), la=(40, 120)))),
    E("butt_kicks", H, CARDIO, "Butt Kicks", "बट किक्स", "butt kicks",
      ["cardio", "hamstrings"], ["none"], "beginner", "3 × 30 s",
      ["Jog on the spot, kicking your heels up towards your glutes.", "Stay light on your feet and keep a quick pace."],
      ["Leaning forward", "Heavy landings"],
      ["knee pain"], ["cardio", "warm up", "hamstrings", "fat loss", *NOEQ],
      side(dict(ll=(-10, -160), la=(-30, 50)), dict(rl=(-10, -160), la=(30, 120)))),
    E("burpee", H, CARDIO, "Burpee", "बर्पी", "burpee, burpees",
      ["full body", "cardio", "chest", "quads"], ["none"], "advanced", "3 × 8–12",
      ["From standing, squat and place your hands on the floor.", "Jump the feet back into a plank.",
       "Jump the feet back in and stand up (add a jump for more intensity)."],
      ["Sagging hips in the plank", "Landing with straight knees"],
      ["knee pain", "wrist pain", "high blood pressure", "pregnancy"], ["full body", "fat loss", "vajan kam", "hiit", "calories", "stamina"],
      side(STAND_UP, PLANK)),
    E("mountain_climbers", H, CARDIO, "Mountain Climbers", "माउंटेन क्लाइंबर", "mountain climber",
      ["core", "cardio", "shoulders"], ["none"], "intermediate", "3 × 20–40 s",
      ["Start in a high plank, hands under the shoulders.", "Drive one knee towards your chest, then switch quickly.",
       "Keep the hips level."],
      ["Hips bouncing up", "Hands too far forward"],
      ["wrist pain", "shoulder injury", "pregnancy"], ["cardio", "core", "pet", "belly fat", "fat loss", "hiit"],
      side(PLANK, MOUNTAIN_CLIMBER, [5, 6, 11, 12]), aliases=["Mountain Climbers"]),
    E("skipping", H, CARDIO, "Skipping Rope", "रस्सी कूद", "skipping, rassi kood, jump rope",
      ["cardio", "calves", "shoulders"], ["none"], "intermediate", "5 × 1 min",
      ["Hold the handles at hip height, elbows close.", "Turn the rope with your wrists and jump just high enough to clear it.",
       "Land softly on the balls of your feet."],
      ["Jumping too high", "Turning with the whole arm"],
      ["knee pain", "ankle pain", "pregnancy"], ["rassi", "रस्सी कूद", "cardio", "fat loss", "vajan kam", "stamina", "calves"],
      side(dict(la=(20, 40)), dict(la=(30, 50), ll=(10, -10)))),
    E("stair_climb", H, CARDIO, "Stair Climbing", "सीढ़ियाँ चढ़ना", "stair climbing, seedhi chadhna",
      ["cardio", "quads", "glutes"], ["box/step"], "beginner", "10–15 min",
      ["Walk up a flight of stairs at a steady pace, whole foot on each step.", "Walk down carefully, holding the rail.",
       "Repeat for the set time."],
      ["Leaning heavily on the rail", "Rushing down"],
      ["knee pain (go slower)", "poor balance"], ["stairs", "seedhi", "सीढ़ी", "cardio", "fat loss", "building", "flat"],
      side(STEP_UP, dict(rl=(70, -10), ll=(0, 0)), [12])),
    E("brisk_walk", H, CARDIO, "Brisk Walk / Cycle", "तेज़ चलना / साइकिल", "brisk walk, tez chalna, walking, cycling",
      ["cardio", "full body"], ["none"], "beginner", "20–45 min",
      ["Walk (or cycle) at a pace where you can talk but not sing.", "Swing the arms and stand tall.",
       "Build up the time week by week."],
      ["Going too fast and stopping early", "Poor footwear"],
      [], ["walking", "walk", "tehelna", "टहलना", "cycle", "cardio", "fat loss", "vajan kam", "diabetes", "sugar", "seniors"],
      side(dict(ll=(25, 0), rl=(-20, -30), la=(-25, -10), ra=(25, 50)), dict(ll=(-20, -30), rl=(25, 0), la=(25, 50), ra=(-25, -10))),
      aliases=["Brisk Walk / Cycle"]),
    E("low_impact_intervals", H, CARDIO, "Low-impact Intervals", "लो-इम्पैक्ट इंटरवल", "march, step jacks, low impact cardio",
      ["cardio", "full body"], ["none"], "beginner", "8 × (30 s fast, 30 s easy)",
      ["March on the spot or do step-jacks (step one foot out while raising the arms).", "Go brisk for 30 seconds.",
       "Slow down for 30 seconds, then repeat."],
      ["Holding the breath", "Starting too hard"],
      [], ["low impact", "knee friendly", "no jumping", "cardio", "fat loss", "seniors", "apartment", *NOEQ],
      front(F_STAND, dict(la=(160, 170), ll=(25, 25), rl=(0, 0), spread=1), [11, 12]),
      aliases=["Low-impact Intervals (step jacks, marching)"]),
    E("squat_jumps", H, CARDIO, "Squat Jump", "स्क्वाट जंप", "squat jump, jump squat",
      ["quads", "glutes", "cardio"], ["none"], "advanced", "3 × 8–10",
      ["Squat down with arms back.", "Jump up explosively, swinging the arms up.",
       "Land softly and go straight into the next squat."],
      ["Landing with straight knees", "Knees caving in"],
      ["knee pain", "pregnancy"], ["jump", "power", "fat loss", "hiit", *LEG_KW],
      side(dict(SQUAT, la=(-40, -40)), STAND_UP)),
    E("shadow_boxing", H, CARDIO, "Shadow Boxing", "शैडो बॉक्सिंग", "shadow boxing, boxing",
      ["cardio", "shoulders", "core"], ["none"], "beginner", "3 × 1 min",
      ["Stand in a boxing stance, hands up by your chin.", "Throw straight punches, rotating through the hips.",
       "Keep moving your feet lightly."],
      ["Locking the elbows hard", "Dropping the guard"],
      [], ["boxing", "cardio", "stress", "fat loss", "shoulders", *NOEQ],
      side(dict(la=(150, 30), ra=(160, 20), ll=(15, 0), rl=(-15, 0)), dict(la=(90, 90), ra=(160, 20), ll=(15, 0), rl=(-15, 0)))),

    # ── Mobility & stretching ──
    E("hip_flexor_stretch", H, MOB, "Kneeling Hip Flexor Stretch", "हिप फ्लेक्सर स्ट्रेच", "hip flexor stretch",
      ["hips", "quads"], ["mat"], "beginner", "30–45 s each side",
      ["Kneel on one knee, the other foot forward.", "Tuck the pelvis slightly and shift the hips forward.",
       "Feel the stretch at the front of the back hip."],
      ["Arching the lower back", "Leaning forward"],
      ["knee pain (pad the knee)"], ["hips", "stretch", "desk job", "sitting", "kamar dard", "lower back", "flexibility"],
      side(KNEEL_TALL, dict(torso=180, ll=(80, 0), rl=(-40, -90), la=(0, 0)), [11, 12])),
    E("hamstring_stretch", H, MOB, "Standing Hamstring Stretch", "हैमस्ट्रिंग स्ट्रेच", "hamstring stretch",
      ["hamstrings", "lower back"], ["none"], "beginner", "30 s each side",
      ["Place one heel on a low step, leg straight.", "Hinge forward from the hips with a flat back.",
       "Stop when you feel a stretch behind the thigh."],
      ["Rounding the back", "Bouncing"],
      [], ["stretch", "flexibility", "jangh", "back of thigh", "kamar"],
      side(STAND, dict(torso=120, ll=(0, 0), la=(30, 40)), [11, 12])),
    E("doorway_chest_stretch", H, MOB, "Doorway Chest Stretch", "चेस्ट स्ट्रेच", "chest stretch, doorway stretch",
      ["chest", "shoulders"], ["wall"], "beginner", "30 s",
      ["Place forearms on a door frame, elbows at shoulder height.", "Step one foot through and lean gently forward.",
       "Feel the stretch across the chest."],
      ["Shrugging", "Leaning too hard"],
      ["shoulder dislocation history"], ["posture", "rounded shoulders", "chest", "chhati", "desk job", "office"],
      front(F_PRESS_START, F_PRESS_START, [11, 12])),
    E("neck_stretch", H, MOB, "Neck Stretch", "गर्दन स्ट्रेच", "neck stretch, gardan stretch",
      ["neck", "shoulders"], ["none"], "beginner", "20–30 s each side",
      ["Sit tall and relax the shoulders.", "Tilt one ear towards the shoulder; gently add the hand for a light stretch.",
       "Repeat on the other side; no forcing."],
      ["Pulling hard", "Lifting the opposite shoulder"],
      ["neck injury", "dizziness"], ["neck", "gardan", "गर्दन", "neck pain", "desk job", "office", "stiffness"],
      front(dict(CROSS_LEGGED), dict(CROSS_LEGGED, head=160))),
    E("shoulder_rolls", H, MOB, "Shoulder Rolls & Arm Circles", "कंधे घुमाना", "shoulder rolls, arm circles, kandhe ghumana",
      ["shoulders", "neck"], ["none"], "beginner", "10 each direction",
      ["Stand tall and roll the shoulders up, back and down.", "Then circle straight arms, small to big.",
       "Reverse the direction."],
      ["Rushing", "Shrugging tension"],
      [], ["kandhe", "कंधे", "shoulders", "warm up", "stiffness", "desk job"],
      front(F_STAND, F_ARMS_UP, [11, 12])),
    E("worlds_greatest_stretch", H, MOB, "World's Greatest Stretch", "फुल-बॉडी स्ट्रेच", "worlds greatest stretch",
      ["hips", "hamstrings", "spine"], ["mat"], "intermediate", "5 each side",
      ["Step into a deep lunge, both hands on the floor inside the front foot.", "Drop the back knee if needed.",
       "Rotate and reach the inside arm to the ceiling, then switch."],
      ["Rushing the rotation", "Collapsing the front knee"],
      ["knee pain"], ["warm up", "mobility", "hips", "flexibility", "full body stretch"],
      side(LUNGE, dict(LUNGE, torso=120, la=(40, 40), ra=(170, 170)), [11])),
    E("figure_four_stretch", H, MOB, "Figure-4 Glute Stretch", "ग्लूट स्ट्रेच", "figure four stretch, piriformis stretch",
      ["glutes", "hips", "lower back"], ["mat"], "beginner", "30–45 s each side",
      ["Lie on your back, knees bent.", "Cross one ankle over the opposite knee.",
       "Pull the lower leg towards you until you feel the outer hip stretch."],
      ["Lifting the head", "Forcing the knee"],
      ["knee pain"], ["hips", "kulhe", "sciatica", "kamar dard", "back pain", "stretch"],
      side(SUPINE_KNEES, dict(SUPINE_KNEES, ll=(160, 90)))),
    E("calf_stretch", H, MOB, "Wall Calf Stretch", "पिंडली स्ट्रेच", "calf stretch",
      ["calves"], ["wall"], "beginner", "30 s each side",
      ["Hands on a wall, one foot back with the heel down.", "Lean forward keeping the back leg straight.",
       "Feel the stretch in the calf."],
      ["Heel lifting", "Turning the back foot out"],
      [], ["calves", "pindli", "पिंडली", "heel pain", "running", "stretch"],
      side(dict(torso=165, la=(110, 100), ll=(20, 20), rl=(-30, -30)), dict(torso=155, la=(110, 110), ll=(35, 10), rl=(-35, -35)), [11, 12])),
    E("open_book", H, MOB, "Open Book Rotation", "ओपन बुक", "open book stretch, thoracic rotation",
      ["spine", "chest", "shoulders"], ["mat"], "beginner", "8 each side",
      ["Lie on your side, knees bent at 90°, arms together in front.", "Open the top arm to the other side, following it with your eyes.",
       "Return slowly; switch sides."],
      ["Letting the knees separate", "Forcing the arm to the floor"],
      [], ["upper back", "posture", "stiffness", "spine", "desk job", "peeth"],
      side(dict(SUPINE_KNEES, la=(90, 90)), dict(SUPINE_KNEES, la=(-90, -90)))),

    # ── Low impact / seniors ──
    E("sit_to_stand", H, LOW, "Sit-to-stand", "कुर्सी से उठना-बैठना", "sit to stand, chair stand",
      ["quads", "glutes"], ["chair"], "beginner", "3 × 8–12",
      ["Sit on the front of a sturdy chair, feet flat.", "Lean slightly forward and stand up without using the hands.",
       "Sit back down slowly."],
      ["Using the arms to push", "Plopping down"],
      [], ["seniors", "elderly", "budhape", "buzurg", "बुज़ुर्ग", "knees", "ghutne", "chair", "kursi", "balance"],
      side(dict(torso=175, ll=(90, 0), la=(30, 60)), dict(la=(60, 70)), [11, 12])),
    E("seated_march", H, LOW, "Seated Marching", "बैठकर मार्च", "seated march",
      ["hips", "core", "cardio"], ["chair"], "beginner", "3 × 30 s",
      ["Sit tall near the front of a chair.", "Lift one knee, then the other, like marching.",
       "Swing the arms for more effort."],
      ["Slumping back", "Holding the breath"],
      [], ["seniors", "buzurg", "बुज़ुर्ग", "chair", "low impact", "knee friendly", "diabetes"],
      side(dict(torso=180, ll=(90, 0), la=(0, 70)), dict(torso=180, ll=(115, 10), la=(0, 70)))),
    E("wall_push_up", H, LOW, "Wall Push-up", "दीवार पर पुश-अप", "wall push up, deewar pushup",
      ["chest", "triceps", "shoulders"], ["wall"], "beginner", "3 × 10–15",
      ["Stand an arm's length from a wall, hands on it at shoulder height.", "Bend the elbows to bring your chest towards the wall.",
       "Push back to straight arms."],
      ["Sagging hips", "Feet too close"],
      [], ["seniors", "buzurg", "wall", "deewar", "दीवार", "chest", "easy", "beginner"],
      side(dict(torso=165, ll=(-15, -15), la=(95, 95)), dict(torso=160, ll=(-20, -20), la=(-20, 95)), [11, 12])),
    E("standing_hip_abduction", H, LOW, "Standing Side Leg Raise", "साइड लेग रेज़", "side leg raise, hip abduction",
      ["hips", "glutes"], ["chair"], "beginner", "2 × 10 each side",
      ["Stand holding the back of a chair.", "Lift one straight leg out to the side.",
       "Lower slowly; keep the body upright."],
      ["Leaning the body over", "Swinging the leg"],
      [], ["hips", "balance", "seniors", "fall prevention", "kulhe", "outer thigh"],
      front(F_STAND, dict(la=(10, 4), rl=(35, 35)), [11])),
    E("heel_toe_walk", H, LOW, "Heel-to-toe Walk", "एड़ी-पंजा चाल", "heel to toe walk, tandem walk",
      ["calves", "core"], ["none"], "beginner", "2 × 10 steps",
      ["Walk in a straight line, placing the heel right in front of the other toe.", "Look ahead, arms out for balance.",
       "Stay near a wall or rail."],
      ["Looking down", "Rushing"],
      [], ["balance", "santulan", "संतुलन", "seniors", "fall prevention", "buzurg"],
      front(F_ARMS_SIDE, F_ARMS_SIDE, [11, 12])),
    E("seated_knee_extension", H, LOW, "Seated Knee Extension", "बैठकर घुटना सीधा", "seated knee extension, leg extension at home",
      ["quads"], ["chair"], "beginner", "3 × 12 each leg",
      ["Sit tall on a chair.", "Straighten one knee until the leg is level, toes up.",
       "Pause, lower slowly; switch legs."],
      ["Leaning back", "Kicking quickly"],
      [], ["knee pain", "ghutne", "घुटने", "arthritis", "seniors", "quads", "chair"],
      side(dict(torso=180, ll=(90, 0), la=(30, 60)), dict(torso=180, ll=(90, 90), rl=(90, 0), la=(30, 60)))),
    E("ankle_circles", H, LOW, "Ankle & Wrist Circles", "टखने घुमाना", "ankle circles, wrist circles",
      ["calves", "forearms"], ["chair"], "beginner", "10 each direction",
      ["Sit tall, lift one foot slightly.", "Draw slow circles with the ankle, then the other way.",
       "Do the same with the wrists."],
      ["Moving the whole leg"],
      [], ["ankle", "takhna", "joints", "stiffness", "seniors", "warm up", "swelling"],
      side(dict(torso=180, ll=(90, 0), la=(30, 60)), dict(torso=180, ll=(90, 0), la=(30, 60)))),
]
