"""Yoga poses and pranayama, with Sanskrit (Roman + Devanagari) and English names."""
from entry import E
from poses import *  # noqa: F401,F403

Y = "yoga"
YK = ["yoga", "योग", "aasan", "asana"]
PREG = "pregnancy (ask your teacher)"

# extra shapes
NAMASTE = dict(la=(20, 150))
ARMS_BACKBEND = dict(torso=190, la=(190, 190), head=200)
WARRIOR1 = dict(torso=180, ll=(88, 0), rl=(-30, -30), la=(180, 180))
WARRIOR3 = dict(torso=90, ll=(0, 0), rl=(-90, -90), la=(90, 90), head=95)
DANCER = dict(torso=150, ll=(0, 0), rl=(-80, -170), la=(140, 140), ra=(-120, -150))
STAND_BACKBEND = dict(torso=200, la=(-30, 40), head=215)
FORWARD_FOLD = dict(torso=5, ll=(0, 0), la=(0, 0), head=0)
LOW_LUNGE = dict(torso=130, ll=(88, 0), rl=(-50, -90), la=(30, 20))
BOW = dict(torso=110, ll=(-110, 160), la=(-100, -100), head=120)
LOCUST = dict(torso=92, ll=(-108, -108), la=(-92, -92), head=100)
FISH = dict(torso=-115, ll=(90, 90), la=(-80, -100), head=-40)
UP_DOG = dict(torso=128, ll=(-82, -86), la=(0, 0), head=140)
SHOULDER_STAND = dict(torso=0, ll=(180, 180), la=(-90, 170), head=-90)
PLOUGH = dict(torso=0, ll=(-40, -40), la=(90, 90), head=-90)
KNEES_TO_CHEST = dict(torso=-90, ll=(-150, 100), la=(-150, 120))
HAPPY_BABY = dict(torso=-90, ll=(-175, 175), la=(170, 175))
ARDHA_MATSYENDRA = dict(torso=180, ll=(150, 10), rl=(90, -90), la=(60, 90))
SUPINE_TWIST = dict(torso=-90, ll=(150, 70), la=(-90, -90))
F_SEATED = dict(torso=180, ll=(80, -80), la=(30, 80))
F_BUTTERFLY = dict(torso=180, ll=(85, -95), la=(10, 30))
F_MALASANA = dict(torso=180, ll=(55, -10), la=(25, 150), spread=3)
F_NOSE = dict(torso=180, ll=(80, -80), la=(30, 80), ra=(-20, 175))
F_PRASARITA = dict(torso=0, ll=(25, 25), la=(0, 0), spread=4, head=0)
F_SIDE_PLANK = dict(torso=110, ll=(-70, -70), la=(-20, 0), ra=(180, 180))
F_KATI = dict(la=(90, 150), ra=(60, 160))
F_GOMUKH = dict(torso=180, ll=(80, -80), la=(170, -10), ra=(-30, 160))

ENTRIES = [
    # ── Warm-up ──
    E("yoga_cat_cow", Y, "Warm-up", "Cat–Cow", "मार्जरी आसन – बिटिलासन", "marjari asana, cat cow, billi aasan", ["spine", "core", "neck"], ["mat"],
      "beginner", "8–10 breaths", ["Come onto hands and knees, wrists under shoulders, knees under hips.",
       "Inhale: drop the belly, lift the chest and gaze (cow).", "Exhale: round the back and tuck the chin (cat).", "Move slowly with the breath."],
      ["Moving faster than the breath", "Forcing the neck back"], ["wrist pain", "recent back injury"],
      ["kamar dard", "back pain", "कमर दर्द", "spine", "reedh", "stiffness", "warm up", "periods", *YK],
      side(dict(QUADRUPED, head=130), dict(QUADRUPED, head=60)), sanskrit="Marjaryasana–Bitilasana",
      aliases=["Cat–Cow (Marjaryasana–Bitilasana)", "Cat-Cow", "Marjariasana"],
      benefits=["Loosens the spine", "Eases back stiffness", "Links breath and movement"]),
    E("yoga_neck_release", Y, "Warm-up", "Neck & Shoulder Release", "ग्रीवा संचालन", "greeva sanchalan, neck exercise", ["neck", "shoulders"], ["mat"],
      "beginner", "1–2 min", ["Sit tall, shoulders relaxed.", "Slowly tilt the head side to side, then forward and back.",
       "Roll the shoulders backwards a few times.", "Keep every movement slow and pain-free."],
      ["Fast circles of the head", "Forcing the range"], ["neck injury", "vertigo / dizziness"],
      ["gardan", "गर्दन", "neck pain", "cervical", "desk job", "office", "stress", *YK],
      front(F_SEATED, dict(F_SEATED, head=165)), sanskrit="Greeva Sanchalana",
      aliases=["Seated neck & shoulder release", "Neck rotation"], benefits=["Releases neck and shoulder tension", "Helps after long screen time"]),
    E("yoga_shoulder_rotation", Y, "Warm-up", "Shoulder Rotation", "स्कंध चक्र", "skandha chakra, shoulder rotation", ["shoulders"], ["mat"],
      "beginner", "10 each direction", ["Sit tall, fingertips on the shoulders.", "Draw big circles with the elbows.",
       "Reverse after 10 rounds; breathe slowly."], ["Shrugging tension"], ["shoulder dislocation history"],
      ["kandhe", "कंधे", "frozen shoulder", "stiffness", "warm up", *YK],
      front(dict(F_SEATED, la=(30, 170)), dict(F_SEATED, la=(150, 30))), sanskrit="Skandha Chakra",
      benefits=["Loosens stiff shoulders", "Warms up the upper body"]),

    # ── Surya Namaskar ──
    E("yoga_surya_namaskar", Y, "Surya Namaskar", "Sun Salutation", "सूर्य नमस्कार", "surya namaskar, suryanamaskar", ["full body", "spine", "cardio"], ["mat"],
      "intermediate", "3–12 rounds", ["Stand in prayer pose, then sweep the arms up and fold forward.",
       "Step back into a lunge, then plank, lower down (8-point pose) and lift into cobra.",
       "Lift the hips into downward dog, step forward to a lunge and fold.", "Rise with arms up and return to prayer. Repeat on the other leg."],
      ["Holding the breath", "Rushing through positions", "Sagging in the plank"],
      ["high blood pressure (go slow)", "back injury", "wrist pain", PREG],
      ["surya", "सूर्य नमस्कार", "full body", "weight loss", "vajan kam", "morning", "flexibility", "stamina", *YK],
      side(STAND_UP, DOWN_DOG), sanskrit="Surya Namaskar",
      aliases=["Sun Salutation A (Surya Namaskar A)", "Surya Namaskar A", "Sun Salutation"],
      benefits=["Warms and stretches the whole body", "Builds stamina", "Combines movement with breath"]),
    E("yoga_pranamasana", Y, "Surya Namaskar", "Prayer Pose", "प्रणामासन", "pranamasana, pranam asan, namaste pose", ["full body"], ["mat"],
      "beginner", "3–5 breaths", ["Stand with feet together, weight even.", "Bring the palms together in front of the chest.",
       "Relax the shoulders and breathe slowly."], ["Collapsing the chest"], [],
      ["namaste", "prayer", "calm", "focus", "start", *YK], side(STAND, NAMASTE, [11, 12]), sanskrit="Pranamasana",
      benefits=["Centres the mind before practice", "Improves posture awareness"]),
    E("yoga_hasta_uttanasana", Y, "Surya Namaskar", "Raised Arms Pose", "हस्त उत्तानासन", "hasta uttanasana", ["spine", "shoulders", "core"], ["mat"],
      "beginner", "3 breaths", ["From prayer pose, inhale and sweep the arms overhead.", "Lift the chest and lean back slightly, hips steady.",
       "Keep the neck long."], ["Bending only at the lower back", "Tensing the shoulders"], ["low back pain", "dizziness"],
      ["stretch", "spine", "posture", "breathing", *YK], side(NAMASTE, ARMS_BACKBEND, [11, 12]), sanskrit="Hasta Uttanasana",
      benefits=["Stretches the front body", "Expands the chest for breathing"]),
    E("yoga_ashwa_sanchalanasana", Y, "Surya Namaskar", "Low Lunge", "अश्व संचालनासन", "ashwa sanchalanasana, equestrian pose", ["hips", "quads", "spine"], ["mat"],
      "beginner", "3–5 breaths each side", ["From a forward fold, step one leg far back and lower the knee.",
       "Hands beside the front foot, front knee over the ankle.", "Lift the chest and look forward."],
      ["Front knee past the toes", "Collapsing the chest"], ["knee pain"],
      ["hips", "hip flexors", "sitting", "lunge", "flexibility", *YK], side(STAND, LOW_LUNGE, [11]), sanskrit="Ashwa Sanchalanasana",
      benefits=["Opens the hip flexors", "Strengthens the legs"]),
    E("yoga_ashtanga_namaskara", Y, "Surya Namaskar", "Eight-limbed Pose", "अष्टांग नमस्कार", "ashtanga namaskara, ashtang namaskar", ["chest", "shoulders", "triceps"], ["mat"],
      "beginner", "1–2 breaths", ["From plank, lower the knees to the floor.", "Lower the chest and chin between the hands, hips slightly up.",
       "Eight points touch: feet, knees, chest, chin and hands."], ["Dropping the whole body flat"], ["shoulder injury", PREG],
      ["chest", "strength", "surya namaskar", *YK], side(PLANK, dict(torso=100, ll=(-55, -90), la=(-110, 5), head=110)),
      sanskrit="Ashtanga Namaskara", benefits=["Strengthens arms and chest", "Prepares for cobra"]),

    # ── Standing ──
    E("yoga_tadasana", Y, "Standing", "Mountain Pose", "ताड़ासन", "tadasana, tad asan, taadasan, palm tree pose", ["full body", "core", "calves"], ["mat"],
      "beginner", "5–10 breaths", ["Stand tall with feet together or hip-width apart.", "Spread the toes, weight even across both feet.",
       "Lift through the crown; for the palm-tree version raise the arms and rise onto the toes.", "Breathe steadily."],
      ["Locking the knees", "Leaning back"], [], ["height", "lambai", "लंबाई", "posture", "balance", "kids", "beginner", *YK],
      front(F_STAND, F_ARMS_UP, [11, 12]), sanskrit="Tadasana", aliases=["Mountain (Tadasana)", "Palm Tree Pose"],
      benefits=["Improves posture and balance", "Builds body awareness", "Stretches the whole body"]),
    E("yoga_virabhadrasana1", Y, "Standing", "Warrior I", "वीरभद्रासन १", "virabhadrasana 1, warrior one", ["quads", "glutes", "shoulders", "hips"], ["mat"],
      "beginner", "30 s each side", ["Step one foot back, turning it out slightly.", "Bend the front knee over the ankle.",
       "Square the hips forward and raise the arms overhead.", "Hold, breathing deeply; switch sides."],
      ["Front knee past the toes", "Back heel lifting"], ["knee injury", "high blood pressure (keep arms on hips)"],
      ["legs", "pair", "strength", "stamina", "confidence", *YK], side(STAND, WARRIOR1, [11, 12]), sanskrit="Virabhadrasana I",
      aliases=["Warrior I (Virabhadrasana I)"], benefits=["Strengthens the legs", "Opens the hips and chest"]),
    E("yoga_virabhadrasana2", Y, "Standing", "Warrior II", "वीरभद्रासन २", "virabhadrasana 2, warrior two", ["quads", "glutes", "shoulders", "hips"], ["mat"],
      "beginner", "30 s each side", ["Stand with feet wide, front foot turned out.", "Bend the front knee over the ankle.",
       "Stretch the arms out at shoulder height and gaze over the front hand.", "Hold, then switch sides."],
      ["Knee collapsing inward", "Leaning over the front leg"], ["knee injury"],
      ["legs", "pair", "jangh", "stamina", "focus", *YK], front(F_WIDE, F_WARRIOR2, [11, 12]), sanskrit="Virabhadrasana II",
      aliases=["Warrior II (Virabhadrasana II)"], pose_check="warrior2", benefits=["Builds leg strength and stamina", "Opens the hips"]),
    E("yoga_trikonasana", Y, "Standing", "Triangle Pose", "त्रिकोणासन", "trikonasana, trikon asan", ["hamstrings", "obliques", "hips", "spine"], ["mat"],
      "beginner", "30 s each side", ["Stand with feet wide, front foot turned out.", "Reach forward, then lower the hand to the shin or a block.",
       "Raise the other arm to the ceiling; open the chest.", "Keep both legs straight. Switch sides."],
      ["Collapsing the chest down", "Bending the front knee"], ["low blood pressure", "neck pain (look forward)"],
      ["side fat", "waist", "kamar", "flexibility", "digestion", *YK], front(F_WIDE, F_TRIANGLE, [11, 12]), sanskrit="Trikonasana",
      aliases=["Triangle (Trikonasana)"], pose_check="triangle", benefits=["Stretches the sides and hamstrings", "Strengthens the legs"]),
    E("yoga_parsvakonasana", Y, "Standing", "Extended Side Angle", "उत्थित पार्श्वकोणासन", "parsvakonasana, side angle", ["quads", "obliques", "hips"], ["mat"],
      "intermediate", "30 s each side", ["From Warrior II, rest the front forearm on the thigh (or hand to the floor).",
       "Reach the top arm over the ear.", "Make one long line from back heel to fingertips."],
      ["Front knee collapsing", "Dropping the chest"], ["knee injury", "high blood pressure"],
      ["side fat", "waist", "legs", "stretch", *YK], front(F_WARRIOR2, dict(F_WARRIOR2, torso=125, la=(10, 40), ra=(150, 150)), [11, 12]),
      sanskrit="Utthita Parsvakonasana", aliases=["Extended Side Angle (Utthita Parsvakonasana)"],
      benefits=["Stretches the side body", "Strengthens legs and hips"]),
    E("yoga_utkatasana", Y, "Standing", "Chair Pose", "उत्कटासन", "utkatasana, kursi aasan, chair pose", ["quads", "glutes", "core"], ["mat"],
      "beginner", "20–30 s", ["Stand with feet together.", "Bend the knees and sit back as if on a chair, weight in the heels.",
       "Raise the arms alongside the ears."], ["Knees far past the toes", "Arching the lower back"], ["knee injury", "low blood pressure"],
      ["legs", "pair", "jangh", "thighs", "strength", "kursi", *YK], side(STAND, CHAIR, [11, 12]), sanskrit="Utkatasana",
      aliases=["Chair (Utkatasana)"], pose_check="chair", benefits=["Strengthens thighs and glutes", "Builds heat and focus"]),
    E("yoga_goddess", Y, "Standing", "Goddess Pose", "उत्कट कोणासन", "utkata konasana, goddess pose", ["quads", "glutes", "hips"], ["mat"],
      "beginner", "20–30 s", ["Stand with feet wide, toes turned out.", "Bend the knees over the toes and lower the hips.",
       "Arms in a cactus shape, chest lifted."], ["Knees caving inward"], ["knee injury"],
      ["hips", "inner thigh", "women", "pelvic floor", "legs", *YK], front(F_WIDE, F_GODDESS, [11, 12]), sanskrit="Utkata Konasana",
      aliases=["Goddess (Utkata Konasana)"], benefits=["Strengthens legs and hips", "Opens the hips"]),
    E("yoga_ardha_chakrasana", Y, "Standing", "Standing Backward Bend", "अर्ध चक्रासन", "ardha chakrasana, half wheel", ["spine", "chest", "hips"], ["mat"],
      "beginner", "3–5 breaths", ["Stand with feet together, hands supporting the lower back.", "Inhale and gently bend backwards from the upper back.",
       "Keep the knees straight; come up slowly."], ["Dropping the head back hard", "Bending only at the lower back"],
      ["vertigo", "high blood pressure", "back injury"], ["spine", "back", "posture", "chest", "breathing", *YK],
      side(HANDS_HIPS, STAND_BACKBEND, [11, 12]), sanskrit="Ardha Chakrasana", benefits=["Opens the chest", "Counteracts slouching"]),
    E("yoga_katichakrasana", Y, "Standing", "Standing Spinal Twist", "कटिचक्रासन", "katichakrasana, kati chakrasana, waist rotation", ["obliques", "spine", "core"], ["mat"],
      "beginner", "10 each side", ["Stand with feet apart, arms at shoulder height.", "Twist the waist to one side, wrapping the arms around the body.",
       "Look over the shoulder, then twist to the other side."], ["Moving the hips", "Swinging fast"], ["slipped disc", "recent abdominal surgery"],
      ["waist", "kamar", "कमर", "side fat", "digestion", "kabz", "constipation", *YK], front(F_ARMS_SIDE, F_KATI, [11, 12]),
      sanskrit="Katichakrasana", benefits=["Loosens the waist and spine", "Supports digestion"]),
    E("yoga_prasarita", Y, "Standing", "Wide-legged Forward Bend", "प्रसारित पादोत्तानासन", "prasarita padottanasana, wide leg forward bend", ["hamstrings", "spine", "hips"], ["mat"],
      "beginner", "30 s", ["Stand with feet wide, hands on hips.", "Fold forward from the hips with a long back.",
       "Place the hands on the floor; let the head hang."], ["Rounding from the upper back", "Locking the knees hard"],
      ["low blood pressure", "glaucoma", "high blood pressure"], ["hamstrings", "flexibility", "calm", "stretch", *YK],
      front(F_WIDE, F_PRASARITA, [11, 12]), sanskrit="Prasarita Padottanasana", benefits=["Stretches the hamstrings", "Calms the mind"]),

    # ── Balance ──
    E("yoga_vrikshasana", Y, "Balance", "Tree Pose", "वृक्षासन", "vrikshasana, vriksh asan, tree pose", ["calves", "core", "hips"], ["mat"],
      "beginner", "30 s each side", ["Stand on one leg, the other foot on the inner calf or thigh (not the knee).",
       "Press foot and leg together.", "Bring the palms together at the chest or overhead and gaze at one point."],
      ["Foot on the knee joint", "Hip sticking out"], ["poor balance (stand by a wall)", "ankle injury"],
      ["balance", "santulan", "संतुलन", "focus", "concentration", "kids", "posture", *YK], front(F_STAND, F_TREE, [11]), sanskrit="Vrikshasana",
      aliases=["Tree (Vrikshasana)"], pose_check="tree", benefits=["Improves balance and focus", "Strengthens ankles and legs"]),
    E("yoga_virabhadrasana3", Y, "Balance", "Warrior III", "वीरभद्रासन ३", "virabhadrasana 3, warrior three", ["glutes", "hamstrings", "core"], ["mat"],
      "intermediate", "15–30 s each side", ["Stand on one leg and hinge forward.", "Lift the back leg until body and leg form a line.",
       "Reach the arms forward; keep the hips level."], ["Hip of the lifted leg opening up", "Rounding the back"],
      ["high blood pressure", "back injury", "poor balance"], ["balance", "santulan", "glutes", "core", "focus", *YK],
      side(STAND, WARRIOR3, [11]), sanskrit="Virabhadrasana III", aliases=["Warrior III (Virabhadrasana III)"],
      benefits=["Builds balance and core strength", "Strengthens the standing leg"]),
    E("yoga_garudasana", Y, "Balance", "Eagle Pose", "गरुड़ासन", "garudasana, garud asan, eagle pose", ["shoulders", "hips", "quads"], ["mat"],
      "intermediate", "20–30 s each side", ["Bend the knees slightly and cross one thigh over the other.", "Wrap the arms, one elbow over the other.",
       "Sink lower and keep the chest lifted."], ["Leaning forward", "Forcing the wrap"], ["knee injury", "shoulder injury"],
      ["balance", "shoulders", "kandhe", "focus", *YK], side(STAND, dict(HALF_SQUAT, la=(80, 160)), [11, 12]), sanskrit="Garudasana",
      aliases=["Eagle (Garudasana)"], benefits=["Improves balance", "Stretches shoulders and upper back"]),
    E("yoga_natarajasana", Y, "Balance", "Dancer Pose", "नटराजासन", "natarajasana, dancer pose", ["quads", "shoulders", "spine", "hips"], ["mat"],
      "advanced", "15–20 s each side", ["Stand on one leg, hold the other ankle behind you.", "Reach the free arm forward.",
       "Kick the foot into the hand and tilt the chest forward."], ["Twisting the hips open", "Locking the standing knee"],
      ["poor balance", "back injury"], ["balance", "santulan", "flexibility", "backbend", *YK], side(STAND, DANCER, [11]),
      sanskrit="Natarajasana", benefits=["Improves balance", "Opens shoulders, chest and hips"]),

    # ── Backbends ──
    E("yoga_bhujangasana", Y, "Backbends", "Cobra Pose", "भुजंगासन", "bhujangasana, bhujang asan, cobra", ["spine", "lower back", "chest"], ["mat"],
      "beginner", "15–30 s", ["Lie face down, hands under the shoulders.", "Press lightly and lift the chest, elbows bent and close.",
       "Shoulders away from the ears; lower slowly."], ["Pushing into the lower back", "Shrugging"],
      ["pregnancy", "recent abdominal surgery", "hernia"], ["kamar dard", "back pain", "कमर", "spine", "posture", "pet", "thyroid", *YK],
      side(PRONE, COBRA), sanskrit="Bhujangasana", aliases=["Cobra (Bhujangasana)"], pose_check="cobra",
      benefits=["Strengthens the back", "Opens the chest", "Can ease mild back stiffness"]),
    E("yoga_sphinx", Y, "Backbends", "Sphinx Pose", "सालम्ब भुजंगासन", "salamba bhujangasana, sphinx", ["spine", "lower back"], ["mat"],
      "beginner", "30–60 s", ["Lie face down, forearms on the floor, elbows under shoulders.", "Lift the chest gently.",
       "Relax the legs and breathe."], ["Collapsing into the shoulders"], ["pregnancy"],
      ["back pain", "kamar", "gentle", "posture", *YK], side(PRONE, SPHINX), sanskrit="Salamba Bhujangasana",
      aliases=["Sphinx (Salamba Bhujangasana)"], benefits=["Gentle back strengthening", "Opens the chest"]),
    E("yoga_setu_bandhasana", Y, "Backbends", "Bridge Pose", "सेतु बंधासन", "setu bandhasana, setu bandh, bridge", ["glutes", "hamstrings", "spine"], ["mat"],
      "beginner", "20–30 s", ["Lie on your back, knees bent, feet hip-width.", "Press the feet down and lift the hips.",
       "Interlace the hands under you; keep the neck still."], ["Turning the head", "Knees falling apart"], ["neck injury"],
      ["kamar", "back pain", "thyroid", "glutes", "periods", "PCOD", *YK], side(SUPINE_KNEES, BRIDGE), sanskrit="Setu Bandhasana",
      aliases=["Bridge (Setu Bandhasana)"], pose_check="bridge", benefits=["Strengthens back and glutes", "Opens the chest"]),
    E("yoga_ustrasana", Y, "Backbends", "Camel Pose", "उष्ट्रासन", "ustrasana, ushtrasana, camel", ["spine", "chest", "hips"], ["mat"],
      "intermediate", "15–30 s", ["Kneel with knees hip-width, hands on the lower back.", "Lift the chest and lean back, hips over the knees.",
       "Reach for the heels if comfortable; come up slowly."], ["Dropping the head back hard", "Hips moving back"],
      ["back injury", "neck injury", "high or low blood pressure", "knee injury"], ["backbend", "chest", "posture", "thyroid", *YK],
      side(KNEEL_TALL, CAMEL), sanskrit="Ustrasana", aliases=["Camel (Ustrasana)"], benefits=["Opens the chest and hip flexors", "Improves posture"]),
    E("yoga_dhanurasana", Y, "Backbends", "Bow Pose", "धनुरासन", "dhanurasana, dhanur asan, bow pose", ["spine", "quads", "chest"], ["mat"],
      "intermediate", "15–20 s", ["Lie face down, bend the knees and hold the ankles.", "Kick the feet into the hands to lift chest and thighs.",
       "Breathe; lower slowly."], ["Knees spreading wide", "Holding the breath"],
      ["pregnancy", "hernia", "high blood pressure", "back injury", "recent abdominal surgery"],
      ["pet", "belly fat", "digestion", "back", "spine", "PCOD", *YK], side(PRONE, BOW), sanskrit="Dhanurasana",
      benefits=["Strengthens the back", "Stretches the front body", "Massages the abdomen"]),
    E("yoga_shalabhasana", Y, "Backbends", "Locust Pose", "शलभासन", "shalabhasana, salabhasana, locust", ["lower back", "glutes", "hamstrings"], ["mat"],
      "beginner", "15–20 s", ["Lie face down, arms by your sides.", "Lift the legs, chest and arms off the floor.",
       "Keep the neck long; lower slowly."], ["Cranking the neck up"], ["pregnancy", "recent back injury"],
      ["kamar", "lower back", "back pain", "slip disc (ask your doctor)", "posture", *YK], side(PRONE, LOCUST),
      sanskrit="Shalabhasana", benefits=["Strengthens the lower back", "Improves posture"]),
    E("yoga_urdhva_mukha", Y, "Backbends", "Upward-facing Dog", "ऊर्ध्व मुख श्वानासन", "urdhva mukha svanasana, upward dog", ["spine", "chest", "triceps"], ["mat"],
      "intermediate", "3–5 breaths", ["From lying face down, press up on straight arms.", "Lift the thighs off the floor, tops of feet down.",
       "Open the chest, shoulders down."], ["Sinking into the shoulders", "Crunching the lower back"], ["wrist pain", "back injury", PREG],
      ["chest", "spine", "surya namaskar", "posture", *YK], side(PRONE, UP_DOG), sanskrit="Urdhva Mukha Svanasana",
      benefits=["Strengthens arms and back", "Opens the chest"]),
    E("yoga_matsyasana", Y, "Backbends", "Fish Pose", "मत्स्यासन", "matsyasana, matsya asan, fish pose", ["chest", "neck", "spine"], ["mat"],
      "intermediate", "15–30 s", ["Lie on your back, hands under the hips.", "Press the forearms down and lift the chest.",
       "Rest the crown of the head lightly on the floor."], ["Putting weight on the head"], ["neck injury", "high or low blood pressure", "migraine"],
      ["chest", "thyroid", "breathing", "posture", *YK], side(SUPINE, FISH), sanskrit="Matsyasana",
      benefits=["Opens the chest and throat", "Counter-pose to shoulder stand"]),

    # ── Forward bends ──
    E("yoga_paschimottanasana", Y, "Forward bends", "Seated Forward Bend", "पश्चिमोत्तानासन", "paschimottanasana, paschimottan", ["hamstrings", "spine", "lower back"], ["mat"],
      "beginner", "30–60 s", ["Sit with legs straight forward.", "Inhale to lengthen; exhale and fold from the hips.",
       "Hold the shins or feet; keep the back long."], ["Rounding hard to reach the toes", "Locking the knees"],
      ["slipped disc", "pregnancy", "recent abdominal surgery"], ["hamstrings", "flexibility", "pet", "digestion", "stress", "calm", *YK],
      side(STAFF, FORWARD_BEND), sanskrit="Paschimottanasana", aliases=["Seated Forward Bend (Paschimottanasana)"],
      benefits=["Stretches the back and hamstrings", "Calms the mind"]),
    E("yoga_uttanasana", Y, "Forward bends", "Standing Forward Bend", "पादहस्तासन", "padahastasana, uttanasana, forward bend", ["hamstrings", "spine", "calves"], ["mat"],
      "beginner", "30 s", ["Stand with feet hip-width.", "Fold forward from the hips; bend the knees as needed.",
       "Let the head and arms hang; rise slowly."], ["Rounding from the upper back", "Coming up fast"],
      ["low blood pressure", "glaucoma", "back injury"], ["hamstrings", "flexibility", "stress", "headache", *YK],
      side(STAND_UP, FORWARD_FOLD, [11, 12]), sanskrit="Padahastasana", aliases=["Uttanasana", "Standing Forward Fold"],
      benefits=["Stretches the back of the legs", "Relaxes the neck and mind"]),
    E("yoga_janu_sirsasana", Y, "Forward bends", "Head-to-knee Pose", "जानु शीर्षासन", "janu sirsasana, janu shirshasana", ["hamstrings", "spine", "hips"], ["mat"],
      "beginner", "30 s each side", ["Sit with one leg straight, the other foot on the inner thigh.", "Turn towards the straight leg.",
       "Fold forward over it with a long back."], ["Forcing the head to the knee"], ["knee injury", "slipped disc"],
      ["hamstrings", "flexibility", "digestion", "calm", *YK], side(dict(STAFF, rl=(80, -80)), dict(FORWARD_BEND, rl=(80, -80))),
      sanskrit="Janu Sirsasana", benefits=["Stretches hamstrings and spine", "Calms the mind"]),

    # ── Seated & hips ──
    E("yoga_dandasana", Y, "Seated & hips", "Staff Pose", "दंडासन", "dandasana, dand asan", ["core", "spine"], ["mat"],
      "beginner", "5 breaths", ["Sit with legs straight together.", "Hands beside the hips, press down to sit tall.",
       "Flex the feet and press the thighs down."], ["Slumping", "Leaning back on the hands"], [],
      ["posture", "spine", "sitting", "beginner", *YK], side(STAFF, dict(STAFF, la=(-10, 0))), sanskrit="Dandasana",
      aliases=["Staff (Dandasana)"], benefits=["Improves sitting posture", "Strengthens the back"]),
    E("yoga_baddha_konasana", Y, "Seated & hips", "Butterfly / Bound Angle", "बद्ध कोणासन", "baddha konasana, titli asan, butterfly", ["hips"], ["mat"],
      "beginner", "1 min", ["Sit tall, bring the soles of the feet together.", "Hold the feet and let the knees drop.",
       "Gently flap the knees like butterfly wings, or hold still."], ["Pushing the knees down with force", "Slumping"],
      ["groin injury", "knee injury"], ["titli", "तितली", "butterfly", "hips", "periods", "PCOD", "pregnancy prep", "women", *YK],
      front(F_SEATED, F_BUTTERFLY), sanskrit="Baddha Konasana", aliases=["Bound Angle (Baddha Konasana)", "Titli Asana", "Butterfly Pose"],
      benefits=["Opens the hips", "Often used for menstrual comfort"]),
    E("yoga_sukhasana", Y, "Seated & hips", "Easy Pose", "सुखासन", "sukhasana, sukh asan, cross legged", ["hips", "spine"], ["mat"],
      "beginner", "1–5 min", ["Sit cross-legged, hands on the knees.", "Lengthen the spine, relax the shoulders.",
       "Sit on a cushion if the knees are high."], ["Slumping"], ["knee injury"],
      ["meditation", "dhyan", "ध्यान", "calm", "stress", "beginner", *YK], front(F_SEATED, F_SEATED), sanskrit="Sukhasana",
      benefits=["Comfortable seat for breathing and meditation", "Opens the hips"]),
    E("yoga_padmasana", Y, "Seated & hips", "Lotus Pose", "पद्मासन", "padmasana, padm asan, lotus", ["hips", "spine"], ["mat"],
      "advanced", "1–5 min", ["Sit and place one foot on the opposite thigh, then the other.", "Rest the hands on the knees.",
       "Sit tall; use half-lotus if the knees complain."], ["Forcing the knees", "Slumping"], ["knee injury", "ankle injury"],
      ["meditation", "dhyan", "ध्यान", "calm", "focus", *YK], front(F_SEATED, dict(F_SEATED, ll=(70, -110))), sanskrit="Padmasana",
      benefits=["Steady seat for meditation", "Calms the mind"]),
    E("yoga_vajrasana", Y, "Seated & hips", "Thunderbolt Pose", "वज्रासन", "vajrasana, vajra asan, diamond pose", ["quads", "calves", "spine"], ["mat"],
      "beginner", "2–5 min (after meals is fine)", ["Kneel and sit back on your heels, big toes touching.", "Hands on the thighs, spine tall.",
       "Breathe slowly."], ["Slumping", "Sitting on painful knees (add a cushion)"], ["knee injury", "ankle injury"],
      ["digestion", "pachan", "पाचन", "after food", "gas", "acidity", "meditation", *YK], side(KNEEL_TALL, VAJRASANA), sanskrit="Vajrasana",
      benefits=["Traditionally done after meals to support digestion", "Steady seat for breathing"]),
    E("yoga_gomukhasana", Y, "Seated & hips", "Cow Face Pose", "गोमुखासन", "gomukhasana, gomukh asan", ["hips", "shoulders", "triceps"], ["mat"],
      "intermediate", "30 s each side", ["Sit and stack one knee over the other.", "Reach one arm up and bend it behind the head, the other behind the back.",
       "Clasp the fingers (or hold a towel)."], ["Forcing the hands together", "Leaning sideways"], ["shoulder injury", "knee injury"],
      ["shoulders", "kandhe", "hips", "posture", "frozen shoulder", *YK], front(F_SEATED, F_GOMUKH), sanskrit="Gomukhasana",
      benefits=["Stretches shoulders and hips"]),
    E("yoga_malasana", Y, "Seated & hips", "Garland Pose (Yogic Squat)", "मालासन", "malasana, garland pose, yoga squat", ["hips", "quads", "calves"], ["mat"],
      "beginner", "30–60 s", ["Squat with feet wider than hips, heels down (use a folded mat under the heels if needed).",
       "Press the elbows against the inner knees, palms together.", "Lengthen the spine."], ["Heels lifting with strain", "Rounding the back"],
      ["knee injury"], ["squat", "hips", "constipation", "kabz", "कब्ज़", "digestion", "pregnancy prep", *YK], front(F_STAND, F_MALASANA, [11, 12]),
      sanskrit="Malasana", benefits=["Opens the hips", "Supports digestion"]),
    E("yoga_mandukasana", Y, "Seated & hips", "Frog Pose (Mandukasana)", "मण्डूकासन", "mandukasana, manduk asan, frog pose", ["core", "spine"], ["mat"],
      "beginner", "20–30 s", ["Sit in Vajrasana and make fists, pressing them into the belly beside the navel.",
       "Exhale and bend forward over the fists.", "Hold, then rise slowly."], ["Pressing too hard"],
      ["recent abdominal surgery", "pregnancy", "ulcers", "back injury"], ["diabetes", "sugar", "madhumeh", "मधुमेह", "digestion", "pet", *YK],
      side(VAJRASANA, dict(VAJRASANA, torso=110, la=(60, 120), head=100)), sanskrit="Mandukasana",
      benefits=["Massages the abdomen", "Traditionally practised for digestion"]),

    # ── Twists ──
    E("yoga_ardha_matsyendrasana", Y, "Twists", "Half Lord of the Fishes", "अर्ध मत्स्येन्द्रासन", "ardha matsyendrasana, half spinal twist", ["spine", "obliques", "hips"], ["mat"],
      "intermediate", "30 s each side", ["Sit, bend one knee and place that foot outside the other knee.", "Lengthen up, then twist towards the bent knee.",
       "Hug the knee or hook the elbow outside it."], ["Twisting from the neck only", "Slumping"],
      ["slipped disc", "pregnancy", "recent abdominal surgery"], ["twist", "spine", "digestion", "kabz", "back", *YK],
      side(STAFF, ARDHA_MATSYENDRA), sanskrit="Ardha Matsyendrasana", aliases=["Half Lord of the Fishes (Ardha Matsyendrasana)"],
      benefits=["Mobilises the spine", "Supports digestion"]),
    E("yoga_supta_matsyendrasana", Y, "Twists", "Supine Twist", "सुप्त मत्स्येन्द्रासन", "supta matsyendrasana, lying twist", ["spine", "lower back", "glutes"], ["mat"],
      "beginner", "30–60 s each side", ["Lie on your back, arms out wide.", "Draw one knee across the body to the floor.",
       "Keep both shoulders heavy; look the other way."], ["Forcing the knee down"], ["slipped disc (gentle only)", PREG],
      ["kamar dard", "back pain", "sleep", "neend", "relax", *YK], side(SUPINE, SUPINE_TWIST), sanskrit="Supta Matsyendrasana",
      aliases=["Supine Twist (Supta Matsyendrasana)"], benefits=["Releases the lower back", "Relaxing before sleep"]),

    # ── Inversions ──
    E("yoga_adho_mukha", Y, "Inversions", "Downward-facing Dog", "अधोमुख श्वानासन", "adho mukha svanasana, downward dog, parvatasana", ["hamstrings", "shoulders", "calves", "spine"], ["mat"],
      "beginner", "5 breaths", ["From hands and knees, lift the hips up and back.", "Press the hands down, lengthen the spine.",
       "Heels reach towards the floor (bend the knees if needed)."], ["Rounding the back", "Shoulders up by the ears"],
      ["wrist pain", "high blood pressure", "glaucoma", "late pregnancy"], ["hamstrings", "shoulders", "full body stretch", "surya namaskar", *YK],
      side(QUADRUPED, DOWN_DOG), sanskrit="Adho Mukha Svanasana", aliases=["Downward Dog (Adho Mukha Svanasana)", "Parvatasana", "Mountain pose (Surya Namaskar)"],
      pose_check="downdog", benefits=["Stretches the back of the body", "Strengthens arms and shoulders"]),
    E("yoga_viparita_karani", Y, "Inversions", "Legs up the Wall", "विपरीत करणी", "viparita karani, legs up wall", ["hamstrings", "lower back"], ["mat", "wall"],
      "beginner", "3–5 min", ["Sit sideways to a wall, then swing the legs up as you lie back.", "Rest the arms by your sides.",
       "Breathe slowly; bend the knees to come out."], ["Straining the legs"], ["glaucoma", "late pregnancy"],
      ["relax", "sleep", "neend", "नींद", "tired legs", "swelling", "stress", "tanav", *YK], side(SUPINE, LEGS_UP), sanskrit="Viparita Karani",
      aliases=["Legs up the Wall (Viparita Karani)"], benefits=["Relaxes the body", "Eases tired legs"]),
    E("yoga_sarvangasana", Y, "Inversions", "Shoulder Stand", "सर्वांगासन", "sarvangasana, sarvang asan, shoulder stand", ["core", "shoulders", "neck"], ["mat"],
      "advanced", "30 s–2 min", ["Lie on your back and lift the legs and hips up.", "Support the back with the hands, elbows on the floor.",
       "Straighten the body up; keep the neck still. Come down slowly."], ["Turning the head", "Weight on the neck"],
      ["neck injury", "high blood pressure", "glaucoma", "heart conditions", "pregnancy", "during periods (traditional advice)"],
      ["thyroid", "inversion", "advanced", *YK], side(LEGS_UP, SHOULDER_STAND), sanskrit="Sarvangasana",
      benefits=["Classic inversion in Indian yoga practice", "Strengthens the core"]),
    E("yoga_halasana", Y, "Inversions", "Plough Pose", "हलासन", "halasana, hal asan, plough", ["spine", "hamstrings", "shoulders"], ["mat"],
      "advanced", "30 s", ["From shoulder stand, lower the feet over the head towards the floor.", "Keep the arms on the floor or support the back.",
       "Roll down slowly, vertebra by vertebra."], ["Turning the head", "Forcing the feet to the floor"],
      ["neck injury", "high blood pressure", "pregnancy", "slipped disc"], ["spine", "thyroid", "flexibility", "advanced", *YK],
      side(SHOULDER_STAND, PLOUGH), sanskrit="Halasana", benefits=["Deep stretch for the spine and hamstrings"]),

    # ── Core ──
    E("yoga_naukasana", Y, "Core", "Boat Pose", "नौकासन", "naukasana, navasana, boat pose", ["core", "hips"], ["mat"],
      "intermediate", "15–30 s", ["Sit with knees bent, lean back slightly.", "Lift the feet and balance on the sit bones.",
       "Straighten the legs if you can; arms forward."], ["Rounding the back", "Holding the breath"],
      ["lower back pain", "pregnancy", "recent abdominal surgery"], ["pet", "पेट", "abs", "belly fat", "core", *YK],
      side(dict(STAFF, ll=(130, 10)), BOAT), sanskrit="Navasana", aliases=["Boat (Navasana)", "Naukasana"],
      benefits=["Strengthens the core", "Improves balance"]),
    E("yoga_plank", Y, "Core", "Plank Pose", "फलकासन", "phalakasana, kumbhakasana, plank", ["core", "shoulders"], ["mat"],
      "beginner", "20–60 s", ["From hands and knees, step the feet back.", "Hands under shoulders, body in one straight line.",
       "Breathe steadily."], ["Hips sagging", "Hips too high"], ["wrist pain", "late pregnancy"],
      ["core", "pet", "strength", "surya namaskar", *YK], side(QUADRUPED, PLANK, [5, 6, 11, 12]), sanskrit="Phalakasana",
      aliases=["Forearm Plank", "Kumbhakasana"], pose_check="plank", benefits=["Builds core and shoulder strength"]),
    E("yoga_chaturanga", Y, "Core", "Four-limbed Staff", "चतुरंग दंडासन", "chaturanga dandasana, chaturanga", ["triceps", "chest", "core"], ["mat"],
      "advanced", "1–3 breaths", ["From plank, shift forward slightly.", "Lower until elbows are at 90°, close to the ribs.",
       "Hold the body straight; lower knees to make it easier."], ["Dropping the shoulders below the elbows", "Sagging hips"],
      ["shoulder injury", "wrist pain", PREG], ["strength", "arms", "core", "surya namaskar", *YK], side(PLANK, PUSHUP_LOW, [5, 6, 11, 12]),
      sanskrit="Chaturanga Dandasana", benefits=["Builds arm and core strength"]),
    E("yoga_vasisthasana", Y, "Core", "Side Plank", "वसिष्ठासन", "vasisthasana, side plank", ["obliques", "shoulders", "core"], ["mat"],
      "intermediate", "15–30 s each side", ["From plank, turn onto one hand and the side of one foot.", "Lift the hips and raise the top arm.",
       "Lower the bottom knee to make it easier."], ["Hips dropping"], ["wrist injury", "shoulder injury"],
      ["side fat", "obliques", "balance", "core", *YK], front(dict(F_SIDE_PLANK, ra=(-20, 0)), F_SIDE_PLANK), sanskrit="Vasisthasana",
      benefits=["Strengthens the side body and shoulders", "Improves balance"]),

    # ── Restorative ──
    E("yoga_balasana", Y, "Restorative", "Child's Pose", "बालासन", "balasana, bal asan, child pose", ["lower back", "hips", "spine"], ["mat"],
      "beginner", "1–3 min", ["Kneel, big toes together, knees apart or together.", "Sit back on the heels and fold forward.",
       "Rest the forehead down, arms forward or by your sides."], ["Forcing the hips to the heels"], ["knee injury", "late pregnancy (knees wide)"],
      ["rest", "relax", "kamar dard", "back pain", "stress", "tanav", "periods", *YK], side(VAJRASANA, CHILD), sanskrit="Balasana",
      aliases=["Child's Pose (Balasana)"], benefits=["Releases the back", "Calms the mind"]),
    E("yoga_shavasana", Y, "Restorative", "Corpse Pose", "शवासन", "shavasana, savasana, shav asan, relaxation", ["full body"], ["mat"],
      "beginner", "5–10 min", ["Lie on your back, legs apart, arms slightly away from the body.", "Close the eyes and let the body feel heavy.",
       "Breathe naturally; relax from toes to head."], ["Fidgeting", "Falling asleep (fine sometimes!)"], [],
      ["relax", "sleep", "neend", "नींद", "stress", "tanav", "तनाव", "blood pressure", "anxiety", *YK], side(SUPINE, SUPINE), sanskrit="Savasana",
      aliases=["Corpse (Savasana)", "Shavasana"], benefits=["Deep relaxation", "Lowers stress"]),
    E("yoga_makarasana", Y, "Restorative", "Crocodile Pose", "मकरासन", "makarasana, makar asan, crocodile", ["lower back", "spine"], ["mat"],
      "beginner", "2–5 min", ["Lie face down, legs apart.", "Fold the arms and rest the forehead on them.",
       "Breathe into the belly and relax."], ["Tensing the shoulders"], ["late pregnancy"],
      ["back pain", "kamar", "relax", "slip disc", "breathing", "asthma", *YK], side(PRONE, dict(PRONE, la=(150, -100))), sanskrit="Makarasana",
      benefits=["Relaxes the back", "Encourages belly breathing"]),
    E("yoga_pawanmuktasana", Y, "Restorative", "Wind-relieving Pose", "पवनमुक्तासन", "pawanmuktasana, pavanmuktasana", ["lower back", "hips", "core"], ["mat"],
      "beginner", "30 s", ["Lie on your back and hug both knees to the chest.", "Optionally lift the head towards the knees.",
       "Rock gently side to side."], ["Straining the neck"], ["recent abdominal surgery", "pregnancy", "hernia"],
      ["gas", "acidity", "digestion", "kabz", "कब्ज़", "constipation", "kamar", *YK], side(SUPINE, KNEES_TO_CHEST), sanskrit="Pawanmuktasana",
      benefits=["Releases the lower back", "Traditionally used to relieve gas"]),
    E("yoga_happy_baby", Y, "Restorative", "Happy Baby", "आनंद बालासन", "ananda balasana, happy baby", ["hips", "lower back", "hamstrings"], ["mat"],
      "beginner", "30–60 s", ["Lie on your back, knees towards the armpits.", "Hold the outer feet, soles to the ceiling.",
       "Rock gently."], ["Lifting the tailbone"], [PREG],
      ["hips", "relax", "lower back", "kamar", *YK], side(KNEES_TO_CHEST, HAPPY_BABY), sanskrit="Ananda Balasana",
      benefits=["Opens the hips", "Releases the lower back"]),

    # ── Pranayama ──
    E("yoga_anulom_vilom", Y, "Pranayama (breathing)", "Alternate Nostril Breathing", "अनुलोम विलोम", "anulom vilom, nadi shodhan, anulom", ["full body"], ["mat"],
      "beginner", "5–10 min", ["Sit comfortably with a tall spine.", "Close the right nostril with the thumb and breathe in through the left.",
       "Close the left with the ring finger, breathe out through the right; then in through the right.", "Continue alternating, slow and even."],
      ["Forcing or holding the breath", "Slouching"], ["blocked nose (wait till clear)"],
      ["breathing", "saans", "सांस", "stress", "tanav", "BP", "blood pressure", "anxiety", "focus", "sleep", *YK], front(F_SEATED, F_NOSE),
      sanskrit="Nadi Shodhana", aliases=["Alternate nostril breathing (Anulom Vilom)", "Anulom Vilom"],
      benefits=["Calms the mind", "Balances the breath", "Helps with stress"]),
    E("yoga_kapalbhati", Y, "Pranayama (breathing)", "Skull-shining Breath", "कपालभाति", "kapalbhati, kapal bhati", ["core"], ["mat"],
      "intermediate", "3 rounds of 20–30 breaths", ["Sit tall, hands on the knees.", "Breathe out sharply through the nose by pulling the belly in.",
       "Let the inhale happen on its own. Start slowly.", "Rest between rounds."],
      ["Forcing the inhale", "Moving the shoulders"],
      ["pregnancy", "high blood pressure", "heart disease", "hernia", "recent abdominal surgery", "epilepsy", "during periods (traditional advice)"],
      ["pet", "पेट", "belly fat", "pet ki charbi", "digestion", "energy", "breathing", *YK], front(F_SEATED, F_SEATED),
      sanskrit="Kapalbhati", benefits=["Energising", "Strengthens the abdominal muscles"]),
    E("yoga_bhramari", Y, "Pranayama (breathing)", "Humming Bee Breath", "भ्रामरी", "bhramari, bhramari pranayama, bee breath", ["full body"], ["mat"],
      "beginner", "5–7 rounds", ["Sit tall, close the ears with the thumbs (fingers over the eyes optional).", "Breathe in through the nose.",
       "Breathe out making a steady humming sound."], ["Pressing hard on the ears"], ["ear infection"],
      ["stress", "tanav", "anxiety", "sleep", "neend", "headache", "calm", "BP", *YK], front(F_SEATED, dict(F_SEATED, la=(-30, 175))),
      sanskrit="Bhramari", aliases=["Humming bee breath (Bhramari)"], benefits=["Calms the mind quickly", "Helps relaxation before sleep"]),
    E("yoga_ujjayi", Y, "Pranayama (breathing)", "Victorious Breath", "उज्जायी", "ujjayi, ujjai", ["full body"], ["mat"],
      "beginner", "3–5 min", ["Sit tall and breathe through the nose.", "Gently narrow the back of the throat so the breath makes a soft ocean sound.",
       "Make the inhale and exhale long and even."], ["Straining the throat"], [],
      ["breathing", "focus", "calm", "thyroid", "asthma", *YK], front(F_SEATED, F_SEATED), sanskrit="Ujjayi",
      benefits=["Slows the breath", "Improves focus during practice"]),
    E("yoga_sheetali", Y, "Pranayama (breathing)", "Cooling Breath", "शीतली", "sheetali, shitali pranayama", ["full body"], ["mat"],
      "beginner", "8–10 rounds", ["Sit tall; roll the tongue into a tube.", "Breathe in through the tongue, feeling the cool air.",
       "Close the mouth and breathe out through the nose."], ["Doing it in cold weather"], ["low blood pressure", "asthma", "cold or cough"],
      ["cooling", "garmi", "गर्मी", "summer", "acidity", "BP", "calm", *YK], front(F_SEATED, F_SEATED), sanskrit="Sheetali",
      benefits=["Cools the body", "Calms the mind"]),
    E("yoga_bhastrika", Y, "Pranayama (breathing)", "Bellows Breath", "भस्त्रिका", "bhastrika, bhastrika pranayama", ["core", "full body"], ["mat"],
      "intermediate", "3 rounds of 10 breaths", ["Sit tall, hands on the knees.", "Breathe in and out forcefully and equally through the nose.",
       "Rest with normal breathing between rounds."], ["Getting dizzy (stop and rest)", "Moving the shoulders"],
      ["high blood pressure", "heart disease", "pregnancy", "hernia", "epilepsy", "vertigo"],
      ["energy", "breathing", "lungs", "winter", *YK], front(F_SEATED, F_SEATED), sanskrit="Bhastrika",
      benefits=["Energising", "Exercises the lungs"]),
]
